from pokemendel_core.data.gen3 import PokemonGen3
from pokemendel_core.data.gen4 import PokemonGen4 as PokemonGen

MOVESETS = {
    1: {
        PokemonGen3.CHARMANDER: ["Growl", "Scratch"],
        PokemonGen3.FLAREON: ["Quick Attack", "Sand Attack", "Tackle", "Ember"],
        PokemonGen3.JOLTEON: ["Quick Attack", "Sand Attack", "Tackle", "Thunder Shock"],
        PokemonGen3.SQUIRTLE: ["Tackle", "Tail Whip"],
        PokemonGen3.VAPOREON: ["Quick Attack", "Sand Attack", "Tackle", "Water Gun"],
    },
    2: {
        PokemonGen3.AERODACTYL: ["Wing Attack"],
        PokemonGen3.ARTICUNO: ["Gust", "Powder Snow"],
        PokemonGen3.BELLSPROUT: ["Vine Whip"],
        PokemonGen3.BULBASAUR: ["Tackle", "Growl"],
        PokemonGen3.CHARMANDER: ["Growl", "Scratch"],
        PokemonGen3.CHIKORITA: ["Growl", "Tackle"],
        PokemonGen3.CLEFFA: ["Charm", "Pound", "Encore"],
        PokemonGen3.CUBONE: ["Growl", "Tail Whip"],
        PokemonGen3.CYNDAQUIL: ["Leer", "Tackle"],
        PokemonGen3.DIGLETT: ["Scratch", "Growl"],
        PokemonGen3.DODUO: ["Growl", "Peck"],
        PokemonGen3.DRATINI: ["Leer", "Wrap"],
        PokemonGen3.EEVEE: ["Tackle", "Tail Whip"],
        PokemonGen3.ESPEON: ["Tackle", "Tail Whip"],
        PokemonGen3.EXEGGCUTE: ["Barrage", "Hypnosis"],
        PokemonGen3.FARFETCHD: ["Peck"],
        PokemonGen3.FLAREON: ["Tackle", "Tail Whip"],
        PokemonGen3.GASTLY: ["Hypnosis", "Lick"],
        PokemonGen3.GEODUDE: ["Tackle"],
        PokemonGen3.GRIMER: ["Poison Gas", "Pound", "Harden"],
        PokemonGen3.GROWLITHE: ["Roar", "Bite"],
        PokemonGen3.HORSEA: ["Bubble"],
        PokemonGen3.JOLTEON: ["Tackle", "Tail Whip"],
        PokemonGen3.KABUTO: ["Harden", "Scratch"],
        PokemonGen3.KRABBY: ["Bubble", "Leer"],
        PokemonGen3.LAPRAS: ["Growl", "Sing", "Water Gun"],
        PokemonGen3.MAGBY: ["Ember"],
        PokemonGen3.MAGIKARP: ["Splash"],
        PokemonGen3.MAGNEMITE: ["Tackle"],
        PokemonGen3.MACHOP: ["Leer", "Low Kick"],
        PokemonGen3.MEW: ["Pound"],
        PokemonGen3.MR_MIME: ["Barrier"],
        PokemonGen3.NIDORAN_F: ["Growl", "Tackle"],
        PokemonGen3.NIDORAN_M: ["Leer", "Tackle"],
        PokemonGen3.PARAS: ["Scratch"],
        PokemonGen3.PICHU: ["Thunder Shock", "Charm"],
        PokemonGen3.PIDGEY: ["Tackle", "Sand Attack"],
        PokemonGen3.POLIWAG: ["Bubble"],
        PokemonGen3.PORYGON: ["Conversion", "Conversion 2", "Tackle"],
        PokemonGen3.PSYDUCK: ["Scratch", "Tail Whip"],
        PokemonGen3.OMANYTE: ["Constrict", "Withdraw"],
        PokemonGen3.ONIX: ["Screech", "Tackle"],
        PokemonGen3.RATTATA: ["Tackle", "Tail Whip"],
        PokemonGen3.SANDSHREW: ["Scratch"],
        PokemonGen3.SEEL: ["Headbutt", "Growl"],
        PokemonGen3.SNORLAX: ["Tackle"],
        PokemonGen3.SMOOCHUM: ["Lick", "Pound"],
        PokemonGen3.STARYU: ["Harden", "Tackle"],
        PokemonGen3.SPEAROW: ["Growl", "Peck"],
        PokemonGen3.SQUIRTLE: ["Tackle", "Tail Whip"],
        PokemonGen3.TANGELA: ["Constrict", "Sleep Powder"],
        PokemonGen3.TENTACOOL: ["Poison Sting"],
        PokemonGen3.TYROGUE: ["Tackle"],
        PokemonGen3.UMBREON: ["Tackle", "Tail Whip"],
        PokemonGen3.VAPOREON: ["Tackle", "Tail Whip"],
        PokemonGen3.VENONAT: ["Disable", "Foresight", "Tackle"],
        PokemonGen3.VOLTORB: ["Tackle"],
        PokemonGen3.VULPIX: ["Ember", "Tail Whip"],
        PokemonGen3.WEEDLE: ["Poison Sting", "String Shot"],
        PokemonGen3.ZAPDOS: ["Peck", "Thunder Shock"],
        PokemonGen3.ZUBAT: ["Leech Life"],
    },
    3: {
        PokemonGen.CHARMANDER: ["Growl", "Scratch"],
        PokemonGen.CHIKORITA: ["Growl", "Tackle"],
        PokemonGen.CYNDAQUIL: ["Leer", "Tackle"],
        PokemonGen.MUDKIP: ["Growl", "Tackle"],
        PokemonGen.SQUIRTLE: ["Tackle", "Tail Whip"],
        PokemonGen.TORCHIC: ["Growl", "Scratch"],
        PokemonGen.TOTODILE: ["Leer", "Scratch"],
        PokemonGen.TREECKO: ["Leer", "Pound"],
    },
    4: {
        PokemonGen.ABRA: ["Teleport"],
        PokemonGen.ABSOL: ["Feint", "Scratch", "Leer"],
        PokemonGen.AERODACTYL: ["Wing Attack", "Supersonic", "Bite", "Scary Face"],
        PokemonGen.AIPOM: ["Scratch", "Sand Attack", "Tail Whip"],
        PokemonGen.ANORITH: ["Harden", "Scratch"],
        PokemonGen.ARCEUS: ["Cosmic Power", "Natural Gift", "Punishment", "Seismic Toss"],
        PokemonGen.ARON: ["Tackle", "Harden"],
        PokemonGen.ARTICUNO: ["Gust", "Powder Snow"],
        PokemonGen.AZELF: ["Confusion", "Rest"],
        PokemonGen.AZURILL: ["Charm", "Splash"],
        PokemonGen.BAGON: ["Rage", "Bite"],
        PokemonGen.BALTOY: ["Confusion", "Harden", "Rapid Spin"],
        PokemonGen.BARBOACH: ["Mud Slap"],
        PokemonGen.BELDUM: ["Take Down"],
        PokemonGen.BELLSPROUT: ["Vine Whip"],
        PokemonGen.BIDOOF: ["Tackle", "Growl"],
        PokemonGen.BONSLY: ["Copycat", "Fake Tears"],
        PokemonGen.BRONZOR: ["Confusion", "Tackle"],
        PokemonGen.BUDEW: ["Absorb", "Growth"],
        PokemonGen.BUIZEL: ["Growl", "Sonic Boom", "Water Sport", "Quick Attack"],
        PokemonGen.BULBASAUR: ["Tackle", "Growl"],
        PokemonGen.BUNEARY: ["Defense Curl", "Foresight", "Pound", "Splash"],
        PokemonGen.BURMY: ["Protect"],
        PokemonGen.CACNEA: ["Leer", "Poison Sting", "Absorb"],
        PokemonGen.CARNIVINE: ["Bind", "Growth"],
        PokemonGen.CARVANHA: ["Leer", "Bite"],
        PokemonGen.CASTFORM: ["Tackle"],
        PokemonGen.CATERPIE: ["String Shot", "Tackle"],
        PokemonGen.CELEBI: ["Confusion", "Recover", "Leech Seed", "Heal Bell"],
        PokemonGen.CHARMANDER: ["Growl", "Scratch"],
        PokemonGen.CHATOT: ["Peck", "Growl"],
        PokemonGen.CHERUBI: ["Tackle"],
        PokemonGen.CHIKORITA: ["Growl", "Tackle"],
        PokemonGen.CHIMCHAR: ["Leer", "Scratch"],
        PokemonGen.CHINCHOU: ["Bubble", "Supersonic"],
        PokemonGen.CHINGLING: ["Wrap"],
        PokemonGen.CLAMPERL: ["Clamp", "Iron Defense", "Water Gun", "Whirlpool"],
        PokemonGen.CLEFFA: ["Charm", "Pound", "Encore"],
        PokemonGen.COMBEE: ["Gust", "Sweet Scent"],
        PokemonGen.CORPHISH: ["Bubble"],
        PokemonGen.CORSOLA: ["Tackle", "Harden"],
        PokemonGen.CRANIDOS: ["Headbutt", "Leer"],
        PokemonGen.CRESSELIA: ["Confusion", "Double Team"],
        PokemonGen.CROAGUNK: ["Astonish", "Mud Slap"],
        PokemonGen.CUBONE: ["Growl", "Tail Whip"],
        PokemonGen.CYNDAQUIL: ["Leer", "Tackle", "Smokescreen"],
        PokemonGen.DARKRAI: ["Disable", "Ominous Wind"],
        PokemonGen.DELIBIRD: ["Present"],
        PokemonGen.DEOXYS: ["Leer", "Wrap"],
        PokemonGen.DIALGA: ["Dragon Breath", "Scary Face"],
        PokemonGen.DIGLETT: ["Scratch", "Growl", "Sand Attack"],
        PokemonGen.DITTO: ["Transform"],
        PokemonGen.DODUO: ["Growl", "Peck", "Quick Attack"],
        PokemonGen.DRATINI: ["Wrap", "Leer", "Thunder Wave"],
        PokemonGen.DRIFLOON: ["Constrict", "Minimize"],
        PokemonGen.DROWZEE: ["Hypnosis", "Pound"],
        PokemonGen.DUNSPARCE: ["Rage", "Defense Curl"],
        PokemonGen.DUSKULL: ["Leer", "Night Shade"],
        PokemonGen.EEVEE: ["Tackle", "Tail Whip", "Helping Hand"],
        PokemonGen.EKANS: ["Wrap", "Leer", "Poison Sting"],
        PokemonGen.ELECTRIKE: ["Tackle", "Thunder Wave"],
        PokemonGen.ELEKID: ["Quick Attack", "Leer"],
        PokemonGen.ENTEI: ["Bite", "Leer"],
        PokemonGen.ESPEON: ["Tackle", "Tail Whip", "Helping Hand"],
        PokemonGen.EXEGGCUTE: ["Barrage", "Hypnosis", "Uproar"],
        PokemonGen.FAN_ROTOM: ["Air Slash", "Confuse Ray", "Thunder Shock", "Thunder Wave"],
        PokemonGen.FARFETCHD: ["Peck", "Sand Attack", "Fury Cutter", "Leer"],
        PokemonGen.FEEBAS: ["Splash"],
        PokemonGen.FINNEON: ["Pound"],
        PokemonGen.FLAREON: ["Tackle", "Tail Whip", "Helping Hand"],
        PokemonGen.FROST_ROTOM: ["Blizzard", "Confuse Ray", "Thunder Shock", "Thunder Wave"],
        PokemonGen.GASTLY: ["Hypnosis", "Lick", "Spite"],
        PokemonGen.GEODUDE: ["Tackle", "Defense Curl", "Mud Sport"],
        PokemonGen.GIBLE: ["Tackle", "Sand Attack"],
        PokemonGen.GIRATINA: ["Dragon Breath", "Scary Face"],
        PokemonGen.GIRATINA_ORIGIN: ["Dragon Breath", "Scary Face"],
        PokemonGen.GIRAFARIG: ["Confusion", "Growl", "Astonish", "Tackle"],
        PokemonGen.GLACEON: ["Tackle", "Tail Whip", "Helping Hand"],
        PokemonGen.GLAMEOW: ["Fake Out", "Scratch"],
        PokemonGen.GLIGAR: ["Poison Sting", "Sand Attack"],
        PokemonGen.GOLDEEN: ["Peck", "Tail Whip", "Water Sport"],
        PokemonGen.GRIMER: ["Poison Gas", "Pound", "Harden"],
        PokemonGen.GROUDON: ["Mud Shot", "Scary Face"],
        PokemonGen.GROWLITHE: ["Roar", "Bite"],
        PokemonGen.GULPIN: ["Pound"],
        PokemonGen.HAPPINY: ["Charm", "Pound", "Copycat"],
        PokemonGen.HEAT_ROTOM: ["Overheat", "Confuse Ray", "Thunder Shock", "Thunder Wave"],
        PokemonGen.HEATRAN: ["Ancient Power"],
        PokemonGen.HERACROSS: ["Endure", "Horn Attack", "Leer", "Tackle"],
        PokemonGen.HIPPOPOTAS: ["Sand Attack", "Tackle"],
        PokemonGen.HO_OH: ["Whirlwind"],
        PokemonGen.HOOTHOOT: ["Foresight", "Growl", "Peck", "Hypnosis"],
        PokemonGen.HOPPIP: ["Splash", "Synthesis"],
        PokemonGen.HORSEA: ["Bubble", "Smokescreen"],
        PokemonGen.HOUNDOUR: ["Ember", "Leer", "Howl"],
        PokemonGen.IGGLYBUFF: ["Pound", "Sing", "Defense Curl"],
        PokemonGen.ILLUMISE: ["Tackle", "Sweet Scent"],
        PokemonGen.JIRACHI: ["Confusion", "Rest", "Wish"],
        PokemonGen.JOLTEON: ["Tackle", "Tail Whip", "Helping Hand", "Sand Attack"],
        PokemonGen.KABUTO: ["Harden", "Scratch"],
        PokemonGen.KANGASKHAN: ["Comet Punch", "Leer"],
        PokemonGen.KECLEON: ["Astonish", "Scratch", "Tail Whip", "Thief"],
        PokemonGen.KOFFING: ["Poison Gas", "Tackle"],
        PokemonGen.KRABBY: ["Bubble", "Mud Sport", "Vise Grip"],
        PokemonGen.KRICKETOT: ["Bide", "Growl"],
        PokemonGen.KYOGRE: ["Water Pulse", "Scary Face"],
        PokemonGen.LAPRAS: ["Growl", "Sing", "Water Gun", "Mist"],
        PokemonGen.LARVITAR: ["Bite", "Leer", "Sandstorm"],
        PokemonGen.LATIAS: ["Psywave", "Wish"],
        PokemonGen.LATIOS: ["Psywave", "Heal Block"],
        PokemonGen.LEAFEON: ["Tackle", "Tail Whip", "Helping Hand"],
        PokemonGen.LEDYBA: ["Tackle"],
        PokemonGen.LICKITUNG: ["Lick", "Supersonic"],
        PokemonGen.LILEEP: ["Astonish", "Constrict"],
        PokemonGen.LOTAD: ["Astonish", "Growl", "Absorb"],
        PokemonGen.LUGIA: ["Whirlwind"],
        PokemonGen.LUNATONE: ["Confusion", "Harden", "Tackle"],
        PokemonGen.LUVDISC: ["Tackle", "Charm"],
        PokemonGen.MACHOP: ["Leer", "Low Kick"],
        PokemonGen.MAGBY: ["Leer", "Smog"],
        PokemonGen.MAGIKARP: ["Splash"],
        PokemonGen.MAGNEMITE: ["Metal Sound", "Tackle"],
        PokemonGen.MAKUHITA: ["Focus Energy", "Tackle", "Sand Attack"],
        PokemonGen.MANAPHY: ["Bubble", "Tail Glow", "Water Sport"],
        PokemonGen.MANKEY: ["Covet", "Leer", "Low Kick", "Scratch"],
        PokemonGen.MANTYKE: ["Bubble", "Tackle", "Supersonic"],
        PokemonGen.MAREEP: ["Tackle", "Growl"],
        PokemonGen.MAWILE: ["Astonish"],
        PokemonGen.MEDITITE: ["Bide", "Meditate"],
        PokemonGen.MEOWTH: ["Growl", "Scratch"],
        PokemonGen.MESPRIT: ["Confusion", "Rest"],
        PokemonGen.MEW: ["Pound", "Transform"],
        PokemonGen.MEWTWO: ["Confusion", "Disable"],
        PokemonGen.MILTANK: ["Growl", "Tackle", "Defense Curl"],
        PokemonGen.MIME_JR: ["Barrier", "Confusion", "Tickle", "Copycat"],
        PokemonGen.MINUN: ["Growl", "Thunder Wave"],
        PokemonGen.MISDREAVUS: ["Growl", "Psywave", "Spite"],
        PokemonGen.MOLTRES: ["Ember", "Wing Attack"],
        PokemonGen.MOW_ROTOM: ["Leaf Storm", "Confuse Ray", "Thunder Shock", "Thunder Wave"],
        PokemonGen.MUDKIP: ["Growl", "Tackle"],
        PokemonGen.MUNCHLAX: ["Metronome", "Odor Sleuth", "Tackle", "Defense Curl"],
        PokemonGen.MURKROW: ["Astonish", "Peck", "Pursuit"],
        PokemonGen.NATU: ["Leer", "Peck"],
        PokemonGen.NIDORAN_F: ["Growl", "Scratch"],
        PokemonGen.NIDORAN_M: ["Leer", "Peck"],
        PokemonGen.NINCADA: ["Harden", "Scratch", "Leech Life"],
        PokemonGen.NOSEPASS: ["Tackle"],
        PokemonGen.NUMEL: ["Growl", "Tackle", "Ember"],
        PokemonGen.ODDISH: ["Absorb", "Sweet Scent"],
        PokemonGen.OMANYTE: ["Constrict", "Withdraw"],
        PokemonGen.ONIX: ["Tackle", "Harden", "Bind", "Mud Sport"],
        PokemonGen.PACHIRISU: ["Bide", "Growl", "Quick Attack"],
        PokemonGen.PALKIA: ["Dragon Breath", "Scary Face"],
        PokemonGen.PARAS: ["Scratch"],
        PokemonGen.PHANPY: ["Defense Curl", "Growl", "Tackle", "Odor Sleuth"],
        PokemonGen.PHIONE: ["Bubble", "Water Sport"],
        PokemonGen.PICHU: ["Charm", "Thunder Shock", "Tail Whip"],
        PokemonGen.PIDGEY: ["Tackle", "Sand Attack"],
        PokemonGen.PINECO: ["Protect", "Tackle"],
        PokemonGen.PINSIR: ["Focus Energy", "Vise Grip", "Bind"],
        PokemonGen.PIPLUP: ["Pound", "Growl"],
        PokemonGen.PLUSLE: ["Growl", "Thunder Wave"],
        PokemonGen.POLIWAG: ["Water Sport", "Bubble"],
        PokemonGen.PONYTA: ["Growl", "Tackle"],
        PokemonGen.POOCHYENA: ["Tackle", "Howl"],
        PokemonGen.PORYGON: ["Conversion", "Conversion 2", "Tackle", "Sharpen"],
        PokemonGen.PSYDUCK: ["Scratch", "Tail Whip", "Water Sport"],
        PokemonGen.QWILFISH: ["Poison Sting", "Spikes", "Tackle"],
        PokemonGen.RAIKOU: ["Bite", "Leer"],
        PokemonGen.RALTS: ["Growl"],
        PokemonGen.RATTATA: ["Tackle", "Tail Whip", "Quick Attack"],
        PokemonGen.RAYQUAZA: ["Twister", "Scary Face"],
        PokemonGen.REGICE: ["Explosion", "Stomp"],
        PokemonGen.REGIGIGAS: ["Confuse Ray", "Dizzy Punch"],
        PokemonGen.REGIROCK: ["Explosion", "Stomp"],
        PokemonGen.REGISTEEL: ["Explosion", "Stomp"],
        PokemonGen.RELICANTH: ["Harden", "Tackle"],
        PokemonGen.REMORAID: ["Water Gun"],
        PokemonGen.RHYHORN: ["Horn Attack", "Tail Whip"],
        PokemonGen.RIOLU: ["Endure", "Foresight", "Quick Attack"],
        PokemonGen.ROTOM: ["Confuse Ray", "Thunder Shock", "Thunder Wave", "Astonish"],
        PokemonGen.SABLEYE: ["Leer", "Scratch", "Foresight"],
        PokemonGen.SANDSHREW: ["Scratch", "Defense Curl"],
        PokemonGen.SCYTHER: ["Leer", "Quick Attack", "Vacuum Wave", "Focus Energy"],
        PokemonGen.SEEDOT: ["Bide", "Harden"],
        PokemonGen.SEEL: ["Headbutt", "Growl"],
        PokemonGen.SENTRET: ["Foresight", "Scratch", "Defense Curl"],
        PokemonGen.SEVIPER: ["Wrap"],
        PokemonGen.SHAYMIN_LAND: ["Growth"],
        PokemonGen.SHAYMIN_SKY: ["Growth"],
        PokemonGen.SHELLDER: ["Tackle", "Withdraw"],
        PokemonGen.SHELLOS: ["Mud Slap", "Mud Sport", "Harden"],
        PokemonGen.SHIELDON: ["Protect", "Tackle"],
        PokemonGen.SHINX: ["Tackle", "Leer"],
        PokemonGen.SHROOMISH: ["Absorb", "Tackle"],
        PokemonGen.SHUCKLE: ["Bide", "Constrict", "Withdraw"],
        PokemonGen.SHUPPET: ["Knock Off", "Screech"],
        PokemonGen.SKARMORY: ["Leer", "Peck"],
        PokemonGen.SKITTY: ["Fake Out", "Foresight", "Tackle", "Tail Whip"],
        PokemonGen.SKORUPI: ["Bite", "Leer", "Poison Sting"],
        PokemonGen.SLAKOTH: ["Scratch", "Yawn"],
        PokemonGen.SLOWPOKE: ["Curse", "Tackle", "Yawn"],
        PokemonGen.SLUGMA: ["Smog", "Yawn"],
        PokemonGen.SMEARGLE: ["Sketch"],
        PokemonGen.SMOOCHUM: ["Lick", "Pound"],
        PokemonGen.SNEASEL: ["Leer", "Scratch", "Taunt"],
        PokemonGen.SNORUNT: ["Leer", "Powder Snow", "Double Team"],
        PokemonGen.SNOVER: ["Leer", "Powder Snow", "Razor Leaf"],
        PokemonGen.SNUBBULL: ["Charm", "Scary Face", "Tackle", "Tail Whip"],
        PokemonGen.SOLROCK: ["Confusion", "Harden", "Tackle"],
        PokemonGen.SPEAROW: ["Growl", "Peck", "Leer"],
        PokemonGen.SPHEAL: ["Defense Curl", "Growl", "Powder Snow", "Water Gun"],
        PokemonGen.SPINARAK: ["Poison Sting", "String Shot", "Scary Face"],
        PokemonGen.SPINDA: ["Tackle", "Uproar"],
        PokemonGen.SPIRITOMB: ["Confuse Ray", "Curse", "Pursuit", "Shadow Sneak"],
        PokemonGen.SPOINK: ["Splash"],
        PokemonGen.SQUIRTLE: ["Tackle", "Tail Whip"],
        PokemonGen.STANTLER: ["Tackle", "Leer"],
        PokemonGen.STARLY: ["Growl", "Tackle", "Quick Attack"],
        PokemonGen.STARYU: ["Harden", "Tackle"],
        PokemonGen.STUNKY: ["Focus Energy", "Scratch", "Poison Gas"],
        PokemonGen.SUICUNE: ["Bite", "Leer"],
        PokemonGen.SUNKERN: ["Absorb", "Growth"],
        PokemonGen.SURSKIT: ["Bubble"],
        PokemonGen.SWABLU: ["Growl", "Peck", "Astonish"],
        PokemonGen.SWINUB: ["Odor Sleuth", "Tackle", "Mud Sport"],
        PokemonGen.TAILLOW: ["Growl", "Peck", "Focus Energy"],
        PokemonGen.TANGELA: ["Constrict", "Sleep Powder", "Ingrain"],
        PokemonGen.TAUROS: ["Tackle", "Tail Whip", "Rage"],
        PokemonGen.TEDDIURSA: ["Fake Tears", "Leer", "Lick", "Scratch"],
        PokemonGen.TENTACOOL: ["Poison Sting", "Supersonic"],
        PokemonGen.TOGEPI: ["Charm", "Growl"],
        PokemonGen.TORCHIC: ["Growl", "Scratch"],
        PokemonGen.TORKOAL: ["Ember", "Smog"],
        PokemonGen.TOTODILE: ["Leer", "Scratch"],
        PokemonGen.TRAPINCH: ["Bite"],
        PokemonGen.TREECKO: ["Leer", "Pound"],
        PokemonGen.TROPIUS: ["Gust", "Leer"],
        PokemonGen.TURTWIG: ["Tackle", "Withdraw"],
        PokemonGen.TYROGUE: ["Fake Out", "Foresight", "Helping Hand", "Tackle"],
        PokemonGen.UMBREON: ["Tackle", "Tail Whip", "Helping Hand"],
        PokemonGen.UNOWN: ["Hidden Power"],
        PokemonGen.UXIE: ["Confusion", "Rest"],
        PokemonGen.VAPOREON: ["Tackle", "Tail Whip", "Helping Hand"],
        PokemonGen.VENONAT: ["Disable", "Foresight", "Tackle", "Supersonic"],
        PokemonGen.VOLBEAT: ["Flash", "Tackle", "Double Team"],
        PokemonGen.VOLTORB: ["Tackle", "Charge"],
        PokemonGen.VULPIX: ["Ember", "Tail Whip"],
        PokemonGen.WAILMER: ["Splash", "Growl"],
        PokemonGen.WASH_ROTOM: ["Hydro Pump", "Confuse Ray", "Thunder Shock", "Thunder Wave"],
        PokemonGen.WEEDLE: ["String Shot", "Poison Sting"],
        PokemonGen.WHISMUR: ["Pound", "Uproar"],
        PokemonGen.WINGULL: ["Growl", "Water Gun"],
        PokemonGen.WOOPER: ["Tail Whip", "Water Gun", "Mud Sport"],
        PokemonGen.WURMPLE: ["String Shot", "Tackle", "Poison Sting"],
        PokemonGen.WYNAUT: ["Splash", "Charm", "Encore"],
        PokemonGen.YANMA: ["Tackle", "Foresight"],
        PokemonGen.ZANGOOSE: ["Leer", "Scratch", "Quick Attack"],
        PokemonGen.ZAPDOS: ["Peck", "Thunder Shock"],
        PokemonGen.ZIGZAGOON: ["Tackle", "Tail Whip", "Growl"],
        PokemonGen.ZUBAT: ["Leech Life", "Supersonic"],
    }
}
