from pokemendel_core.data.gen3 import PokemonGen3

MOVESETS = {
    2: {
        PokemonGen3.AERODACTYL: ["Wing Attack"],
        PokemonGen3.ARTICUNO: ["Gust", "Powder Snow"],
        PokemonGen3.BELLSPROUT: ["Vine Whip"],
        PokemonGen3.BULBASAUR: ["Tackle", "Growl"],
        PokemonGen3.CHARMANDER: ["Growl", "Scratch"],
        PokemonGen3.CLEFFA: ["Charm", "Pound", "Encore"],
        PokemonGen3.CUBONE: ["Growl", "Tail Whip"],
        PokemonGen3.DIGLETT: ["Scratch", "Growl"],
        PokemonGen3.DODUO: ["Growl", "Peck"],
        PokemonGen3.DRATINI: ["Leer", "Wrap"],
        PokemonGen3.EEVEE: ["Tackle", "Tail Whip"],
        PokemonGen3.EXEGGCUTE: ["Barrage", "Hypnosis"],
        PokemonGen3.FARFETCHD: ["Peck"],
        PokemonGen3.GASTLY: ["Hypnosis", "Lick"],
        PokemonGen3.GEODUDE: ["Tackle"],
        PokemonGen3.GRIMER: ["Poison Gas", "Pound", "Harden"],
        PokemonGen3.GROWLITHE: ["Roar", "Bite"],
        PokemonGen3.HORSEA: ["Bubble"],
        PokemonGen3.KABUTO: ["Harden", "Scratch"],
        PokemonGen3.KRABBY: ["Bubble", "Leer"],
        PokemonGen3.LAPRAS: ["Growl", "Sing", "Water Gun"],
        PokemonGen3.MAGBY: ["Ember"],
        PokemonGen3.MAGIKARP: ["Splash"],
        PokemonGen3.MAGNEMITE: ["Tackle"],
        PokemonGen3.MACHOP: ["Leer", "Low Kick"],
        PokemonGen3.MEW: ["Pound"],
        PokemonGen3.MR_MIME: ["Barrier"],
        PokemonGen3.NIDORAN_F: ["Growl", "Tackle"],
        PokemonGen3.NIDORAN_M: ["Leer", "Tackle"],
        PokemonGen3.PARAS: ["Scratch"],
        PokemonGen3.PICHU: ["Thunder Shock", "Charm"],
        PokemonGen3.PIDGEY: ["Tackle", "Sand Attack"],
        PokemonGen3.POLIWAG: ["Bubble"],
        PokemonGen3.PORYGON: ["Conversion", "Conversion 2", "Tackle"],
        PokemonGen3.PSYDUCK: ["Scratch", "Tail Whip"],
        PokemonGen3.OMANYTE: ["Constrict", "Withdraw"],
        PokemonGen3.ONIX: ["Screech", "Tackle"],
        PokemonGen3.RATTATA: ["Tackle", "Tail Whip"],
        PokemonGen3.SANDSHREW: ["Scratch"],
        PokemonGen3.SEEL: ["Headbutt", "Growl"],
        PokemonGen3.SNORLAX: ["Tackle"],
        PokemonGen3.SMOOCHUM: ["Lick", "Pound"],
        PokemonGen3.STARYU: ["Harden", "Tackle"],
        PokemonGen3.SPEAROW: ["Growl", "Peck"],
        PokemonGen3.SQUIRTLE: ["Tackle", "Tail Whip"],
        PokemonGen3.TANGELA: ["Constrict", "Sleep Powder"],
        PokemonGen3.TENTACOOL: ["Poison Sting"],
        PokemonGen3.TYROGUE: ["Tackle"],
        PokemonGen3.VENONAT: ["Disable", "Foresight", "Tackle"],
        PokemonGen3.VOLTORB: ["Tackle"],
        PokemonGen3.VULPIX: ["Ember", "Tail Whip"],
        PokemonGen3.WEEDLE: ["Poison Sting", "String Shot"],
        PokemonGen3.ZAPDOS: ["Peck", "Thunder Shock"],
        PokemonGen3.ZUBAT: ["Leech Life"],
    }
}
