from definitions import Game, GymTrainer, TrainerPokemon, EliteTrainer
from pokemendel_core.utils.definitions import Regions, Types
from pokemendel_core.data import fetch_pokemon
from pokemendel_core.data.gen3 import PokemonGen3
from dataclasses import dataclass


_GENERATION = 3


@dataclass
class _BaseRSGame(Game):
    def __init__(self, **kwargs):
        assert 'name' in kwargs
        for override_field, default_value in [
            ('gen', _GENERATION),
            ('region', Regions.HOENN),
            ('gyms', [
        GymTrainer(
            leader="Roxanne",
            type=Types.ROCK,
            pokemons=[
                TrainerPokemon(PokemonGen3.GEODUDE, 14),
                TrainerPokemon(PokemonGen3.NOSEPASS, 15),
            ],
            location="Rustboro City",
            badge="Stone Badge"
        ),
        GymTrainer(
            leader="Brawly",
            type=Types.FIGHTING,
            pokemons=[
                TrainerPokemon(PokemonGen3.MACHOP, 17),
                TrainerPokemon(PokemonGen3.MAKUHITA, 18),
            ],
            location="Dewford Town",
            badge="Knuckle Badge"
        ),
        GymTrainer(
            leader="Wattson",
            type=Types.ELECTRIC,
            pokemons=[
                TrainerPokemon(PokemonGen3.MAGNEMITE, 22),
                TrainerPokemon(PokemonGen3.VOLTORB, 20),
                TrainerPokemon(PokemonGen3.MAGNETON, 23),
            ],
            location="Mauville City",
            badge="Dynamo Badge"
        ),
        GymTrainer(
            leader="Flannery",
            type=Types.FIRE,
            pokemons=[
                TrainerPokemon(PokemonGen3.SLUGMA, 26),
                TrainerPokemon(PokemonGen3.SLUGMA, 26),
                TrainerPokemon(PokemonGen3.TORKOAL, 28),
            ],
            location="Lavaridge City",
            badge="Heat Badge"
        ),
        GymTrainer(
            leader="Norman",
            type=Types.NORMAL,
            pokemons=[
                TrainerPokemon(PokemonGen3.SLAKING, 28),
                TrainerPokemon(PokemonGen3.VIGOROTH, 30),
                TrainerPokemon(PokemonGen3.SLAKING, 31),
            ],
            location="Petalburg City",
            badge="Balance Badge"
        ),
        GymTrainer(
            leader="Winona",
            type=Types.FLYING,
            pokemons=[
                TrainerPokemon(PokemonGen3.SWELLOW, 31),
                TrainerPokemon(PokemonGen3.PELIPPER, 30),
                TrainerPokemon(PokemonGen3.SKARMORY, 32),
                TrainerPokemon(PokemonGen3.ALTARIA, 33),
            ],
            location="Fortree Town",
            badge="Feather Badge"
        ),
        GymTrainer(
            leader="Tate & Liza",
            type=Types.PSYCHIC,
            pokemons=[
                TrainerPokemon(PokemonGen3.SOLROCK, 42),
                TrainerPokemon(PokemonGen3.LUNATONE, 42),
            ],
            location="Mossdeep City",
            badge="Mind Badge"
        ),
        GymTrainer(
            leader="Wallace",
            type=Types.FIGHTING,
            pokemons=[
                TrainerPokemon(PokemonGen3.LUVDISC, 40),
                TrainerPokemon(PokemonGen3.WHISCASH, 42),
                TrainerPokemon(PokemonGen3.SEALEO, 40),
                TrainerPokemon(PokemonGen3.SEAKING, 42),
                TrainerPokemon(PokemonGen3.MILTOIC, 43),
            ],
            location="Sootopolis City",
            badge="Rain Badge"
        ),
    ]),
            ('elite4', [
        EliteTrainer(
            leader="Sydney", type=Types.DARK, pokemons=[
                TrainerPokemon(PokemonGen3.MIGHTYENA, 46),
                TrainerPokemon(PokemonGen3.CACTURNE, 46),
                TrainerPokemon(PokemonGen3.SHIFTRY, 48),
                TrainerPokemon(PokemonGen3.SHARPEDO, 48),
                TrainerPokemon(PokemonGen3.ABSOL, 49),
            ]
        ),
        EliteTrainer(
            leader="Phoebe", type=Types.GHOST, pokemons=[
                TrainerPokemon(PokemonGen3.DUSCLOPS, 48),
                TrainerPokemon(PokemonGen3.BANETTE, 49),
                TrainerPokemon(PokemonGen3.BANETTE, 49),
                TrainerPokemon(PokemonGen3.SABLEYE, 50),
                TrainerPokemon(PokemonGen3.DUSCLOPS, 51),
            ]
        ),
        EliteTrainer(
            leader="Glacia", type=Types.ICE, pokemons=[
                TrainerPokemon(PokemonGen3.GLALIE, 50),
                TrainerPokemon(PokemonGen3.SEALEO, 50),
                TrainerPokemon(PokemonGen3.GLALIE, 52),
                TrainerPokemon(PokemonGen3.SEALEO, 52),
                TrainerPokemon(PokemonGen3.WALREIN, 53),
            ]
        ),
        EliteTrainer(
            leader="Drake", type=Types.DRAGON, pokemons=[
                TrainerPokemon(PokemonGen3.SHELGON, 52),
                TrainerPokemon(PokemonGen3.ALTARIA, 54),
                TrainerPokemon(PokemonGen3.FLYGON, 53),
                TrainerPokemon(PokemonGen3.FLYGON, 53),
                TrainerPokemon(PokemonGen3.SALAMENCE, 55),
            ]
        ),
        EliteTrainer(
            leader="Steven", type=Types.STEEL, pokemons=[
                TrainerPokemon(PokemonGen3.SKARMORY, 57),
                TrainerPokemon(PokemonGen3.CRADILY, 56),
                TrainerPokemon(PokemonGen3.CLAYDOL, 55),
                TrainerPokemon(PokemonGen3.ARMALDO, 56),
                TrainerPokemon(PokemonGen3.AGGRON, 56),
                TrainerPokemon(PokemonGen3.METAGROSS, 58),
            ]
        ),
    ]),
            ('routes', [
    "Littleroot Town",
    "Oldale Town",
    "Petalburg City",
    "Petalburg Woods",
    "Rustboro City",
    "Rusturf Tunnel",
    "Dewford Town",
    "Granite Cave",
    "Slateport City",
    "Mauville City",
    "Verdanturf Town",
    "Fallarbor Town",
    "Fiery Path",
    "Meteor Falls",
    "Mt. Chimney",
    "Jagged Pass",
    "Lavaridge Town",
    "Desert Underpass",
    "New Mauville",
    "Abandoned Ship",
    "Fortree City",
    "Scorched Slab",
    "Safari Zone",
    "Mt. Pyre",
    "Lilycove City",
    "Team Magma/Aqua Hideout",
    "Mossdeep City",
    "Shoal Cave",
    "Seafloor Cavern",
    "Sootopolis City",
    "Cave of Origin",
    "Mirage Island",
    "Pacifidlog Town",
    "Sealed Chamber",
    "Ever Grande City",
    "Victory Road",
    "Route 101",
    "Route 102",
    "Route 103",
    "Route 104",
    "Route 105",
    "Route 106",
    "Route 107",
    "Route 108",
    "Route 109",
    "Route 110",
    "Route 111",
    "Route 112",
    "Route 113",
    "Route 114",
    "Route 115",
    "Route 116",
    "Route 117",
    "Route 118",
    "Route 119",
    "Route 120",
    "Route 121",
    "Route 122",
    "Route 123",
    "Route 124",
    "Route 125",
    "Route 126",
    "Route 127",
    "Route 128",
    "Route 129",
    "Route 130",
    "Route 131",
    "Route 132",
    "Route 133",
    "Route 134",
    "Altering Cave",
    "Artisan Cave",
    "Battle Frontier",
    "Battle Resort",
    "Battle Tower",
    "Birth Island",
    "Faraway Island",
    "Marine Cave",
    "Mirage Spots",
    "Mirage Tower",
    "Roaming Hoenn",
    "Sea Mauville",
    "Sky Pillar",
    "Southern Island",
    "SS Tidal",
    "Terra Cave",
    "Trainer Hill",
]),
            ('starters', [
        fetch_pokemon(PokemonGen3.TREECKO, _GENERATION),
        fetch_pokemon(PokemonGen3.TORCHIC, _GENERATION),
        fetch_pokemon(PokemonGen3.MUDKIP, _GENERATION),
    ]),
            ('important_battles', [
                "Rustboro City - GymTrainer (15)",
                "Dewford Town - GymTrainer (18)",
                "Route 110 - Rival (20)",
                "Mauville City - Wally (16)",
                "Mauville City - GymTrainer (23)",
                "Mt. Chimney - Boss (25)",
                "Lavaridge City - GymTrainer (28)",
                "Petalburg City - GymTrainer (31)",
                "Weather Institute - Boss (28)"
                "Route 119 - Rival (31)",
                "Fortree Town - GymTrainer (33)",
                "Lilycove City - Rival (34)",
                "Team X Hideout - Boss (32)",
                "Mossdeep City - GymTrainer (42)",
                "Route 128 - Boss (43)",
                "Sootopolis City - GymTrainer (43)",
                "Ever Grand City - Wally (45)",
                "EliteTrainer 4  (58)",
            ]),
            ('egg_pokemons', {
                PokemonGen3.ANORITH, PokemonGen3.LILEEP,
            }),
        ]:
            kwargs[override_field] = kwargs.get(override_field, default_value)
        super().__init__(**kwargs)


RUBY = _BaseRSGame(
    name="Ruby",
    encounters={
        "Route 101": {PokemonGen3.ZIGZAGOON, PokemonGen3.WURMPLE, PokemonGen3.POOCHYENA},
        "Route 102": {PokemonGen3.ZIGZAGOON, PokemonGen3.WURMPLE, PokemonGen3.POOCHYENA, PokemonGen3.RALTS, PokemonGen3.SURSKIT, PokemonGen3.SEEDOT, PokemonGen3.MARILL, PokemonGen3.MAGIKARP, PokemonGen3.GOLDEEN, PokemonGen3.CORPHISH},
        "Route 103": {PokemonGen3.POOCHYENA, PokemonGen3.ZIGZAGOON, PokemonGen3.WINGULL, PokemonGen3.TENTACOOL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 104": {PokemonGen3.ZIGZAGOON, PokemonGen3.WURMPLE, PokemonGen3.TAILLOW, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.MAGIKARP},
        "Route 105": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP, PokemonGen3.REGICE},
        "Route 106": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 107": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 108": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 109": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 110": {PokemonGen3.ELECTRIKE, PokemonGen3.WINGULL, PokemonGen3.ODDISH, PokemonGen3.ZIGZAGOON, PokemonGen3.MINUN, PokemonGen3.PLUSLE, PokemonGen3.GULPIN, PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 111": {PokemonGen3.SANDSHREW, PokemonGen3.TRAPINCH, PokemonGen3.CACNEA, PokemonGen3.BALTOY, PokemonGen3.MARILL, PokemonGen3.SURSKIT, PokemonGen3.BARBOACH, PokemonGen3.MAGIKARP, PokemonGen3.GOLDEEN, PokemonGen3.GEODUDE, PokemonGen3.REGIROCK},
        "Route 112": {PokemonGen3.MACHOP, PokemonGen3.NUMEL},
        "Route 113": {PokemonGen3.SANDSHREW, PokemonGen3.SPINDA, PokemonGen3.SKARMORY},
        "Route 114": {PokemonGen3.SWABLU, PokemonGen3.SURSKIT, PokemonGen3.MARILL, PokemonGen3.BARBOACH, PokemonGen3.MAGIKARP, PokemonGen3.GOLDEEN, PokemonGen3.GEODUDE, PokemonGen3.SEEDOT, PokemonGen3.NUZLEAF, PokemonGen3.ZANGOOSE},
        "Route 115": {PokemonGen3.TAILLOW, PokemonGen3.SWABLU, PokemonGen3.JIGGLYPUFF, PokemonGen3.SWELLOW, PokemonGen3.WINGULL, PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 116": {PokemonGen3.ZIGZAGOON, PokemonGen3.WHISMUR, PokemonGen3.SKITTY, PokemonGen3.TAILLOW, PokemonGen3.NINCADA},
        "Route 117": {PokemonGen3.ZIGZAGOON, PokemonGen3.ROSELIA, PokemonGen3.SURSKIT, PokemonGen3.ODDISH, PokemonGen3.MARILL, PokemonGen3.SURSKIT, PokemonGen3.CORPHISH, PokemonGen3.MAGIKARP, PokemonGen3.ILLUMISE, PokemonGen3.VOLBEAT},
        "Route 118": {PokemonGen3.ZIGZAGOON, PokemonGen3.ELECTRIKE, PokemonGen3.KECLEON, PokemonGen3.LINOONE, PokemonGen3.WINGULL, PokemonGen3.MANECTRIC, PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.CARVANHA, PokemonGen3.SHARPEDO, PokemonGen3.GOLDEEN, PokemonGen3.MAGIKARP},
        "Route 119": {PokemonGen3.ODDISH, PokemonGen3.ZIGZAGOON, PokemonGen3.LINOONE, PokemonGen3.KECLEON, PokemonGen3.TROPIUS, PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.FEEBAS, PokemonGen3.CARVANHA, PokemonGen3.MAGIKARP},
        "Weather Institute": {PokemonGen3.CASTFORM},
        "Route 120": {PokemonGen3.ODDISH, PokemonGen3.LINOONE, PokemonGen3.SURSKIT, PokemonGen3.KECLEON, PokemonGen3.ABSOL, PokemonGen3.MARILL, PokemonGen3.ZIGZAGOON, PokemonGen3.MARILL, PokemonGen3.SURSKIT, PokemonGen3.BARBOACH, PokemonGen3.MAGIKARP, PokemonGen3.GOLDEEN, PokemonGen3.REGISTEEL},
        "Route 121": {PokemonGen3.GLOOM, PokemonGen3.WINGULL, PokemonGen3.KECLEON, PokemonGen3.ODDISH, PokemonGen3.ZIGZAGOON, PokemonGen3.LINOONE, PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP, PokemonGen3.DUSKULL},
        "Route 122": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 123": {PokemonGen3.GLOOM, PokemonGen3.WINGULL, PokemonGen3.KECLEON, PokemonGen3.ODDISH, PokemonGen3.ZIGZAGOON, PokemonGen3.LINOONE, PokemonGen3.TENTACOOL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP, PokemonGen3.DUSKULL},
        "Route 124": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP, PokemonGen3.CLAMPERL, PokemonGen3.CHINCHOU, PokemonGen3.RELICANTH},
        "Route 125": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 126": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP, PokemonGen3.CLAMPERL, PokemonGen3.CHINCHOU, PokemonGen3.RELICANTH},
        "Route 127": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 128": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.LUVDISC, PokemonGen3.CORSOLA, PokemonGen3.MAGIKARP},
        "Route 129": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILORD, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 130": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 131": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 132": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.HORSEA},
        "Route 133": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.HORSEA},
        "Route 134": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.HORSEA},
        "Abandoned Ship": {PokemonGen3.TENTACOOL, PokemonGen3.TENTACRUEL, PokemonGen3.MAGIKARP},
        "Altering Cave": {},
        "Artisan Cave": {},
        "Battle Frontier": {},
        "Battle Resort": {},
        "Battle Tower": {},
        "Birth Island": {},
        "Cave of Origin": {PokemonGen3.ZUBAT, PokemonGen3.GOLDEEN, PokemonGen3.MAWILE, PokemonGen3.GROUDON},
        "Desert Underpass": {},
        "Dewford Town": {PokemonGen3.WAILMER, PokemonGen3.MAGIKARP, PokemonGen3.TENTACOOL},
        "Ever Grande City": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.LUVDISC, PokemonGen3.CORSOLA, PokemonGen3.MAGIKARP},
        "Fallarbor Town": {},
        "Faraway Island": {},
        "Fiery Path": {PokemonGen3.GRIMER, PokemonGen3.KOFFING, PokemonGen3.NUMEL, PokemonGen3.MACHOP, PokemonGen3.SLUGMA, PokemonGen3.TORKOAL},
        "Fortree City": {PokemonGen3.SKITTY, PokemonGen3.PLUSLE},
        "Granite Cave": {PokemonGen3.ZUBAT, PokemonGen3.MAKUHITA, PokemonGen3.ABRA, PokemonGen3.GEODUDE, PokemonGen3.ARON, PokemonGen3.NOSEPASS, PokemonGen3.MAWILE},
        "Jagged Pass": {PokemonGen3.MACHOP, PokemonGen3.NUMEL, PokemonGen3.SPOINK},
        "Lavaridge Town": {},
        "Lilycove City": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.STARYU, PokemonGen3.MAGIKARP},
        "Littleroot Town": {},
        "Marine Cave": {},
        "Mauville City": {},
        "Meteor Falls": {PokemonGen3.ZUBAT, PokemonGen3.GOLBAT, PokemonGen3.BARBOACH, PokemonGen3.MAGIKARP, PokemonGen3.GOLDEEN, PokemonGen3.WHISCASH, PokemonGen3.BAGON, PokemonGen3.SOLROCK},
        "Mirage Island": {PokemonGen3.WYNAUT},
        "Mirage Spots": {},
        "Mirage Tower": {},
        "Mossdeep City": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP, PokemonGen3.BELDUM},
        "Mt. Chimney": {},
        "Mt. Pyre": {PokemonGen3.DUSKULL, PokemonGen3.SHUPPET, PokemonGen3.MEDITITE, PokemonGen3.VULPIX, PokemonGen3.WINGULL, PokemonGen3.CHIMECHO},
        "New Mauville": {PokemonGen3.MAGNEMITE, PokemonGen3.VOLTORB, PokemonGen3.MAGNETON, PokemonGen3.ELECTRODE},
        "Oldale Town": {},
        "Pacifidlog Town": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP, PokemonGen3.CORSOLA},
        "Petalburg City": {PokemonGen3.MARILL, PokemonGen3.CORPHISH, PokemonGen3.MAGIKARP, PokemonGen3.GOLDEEN},
        "Petalburg Woods": {PokemonGen3.ZIGZAGOON, PokemonGen3.WURMPLE, PokemonGen3.TAILLOW, PokemonGen3.SLAKOTH, PokemonGen3.SILCOON, PokemonGen3.CASCOON, PokemonGen3.SHROOMISH},
        "Roaming Hoenn": {PokemonGen3.LATIOS},
        "Rustboro City": {PokemonGen3.MAKUHITA},
        "Rusturf Tunnel": {PokemonGen3.WHISMUR},
        "Safari Zone": {PokemonGen3.ODDISH, PokemonGen3.PHANPY, PokemonGen3.XATU, PokemonGen3.HERACROSS, PokemonGen3.GLOOM, PokemonGen3.NATU, PokemonGen3.GEODUDE, PokemonGen3.RHYHORN, PokemonGen3.DODRIO, PokemonGen3.PINSIR, PokemonGen3.DODUO, PokemonGen3.PSYDUCK, PokemonGen3.GOLDUCK, PokemonGen3.GOLDEEN, PokemonGen3.SEAKING, PokemonGen3.MAGIKARP, PokemonGen3.PIKACHU, PokemonGen3.WOBBUFFET, PokemonGen3.GIRAFARIG},
        "Scorched Slab": {},
        "Sea Mauville": {},
        "Seafloor Cavern": {PokemonGen3.ZUBAT, PokemonGen3.GOLBAT, PokemonGen3.TENTACOOL, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Sealed Chamber": {},
        "Shoal Cave": {PokemonGen3.ZUBAT, PokemonGen3.SPHEAL, PokemonGen3.GOLBAT, PokemonGen3.TENTACOOL, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP, PokemonGen3.SNORUNT},
        "Sky Pillar": {PokemonGen3.GOLBAT, PokemonGen3.CLAYDOL, PokemonGen3.ALTARIA, PokemonGen3.RAYQUAZA, PokemonGen3.MAWILE, PokemonGen3.DUSCLOPS},
        "Slateport City": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Sootopolis City": {PokemonGen3.MAGIKARP, PokemonGen3.GYARADOS, PokemonGen3.TENTACOOL},
        "Southern Island": {PokemonGen3.LATIAS},
        "SS Tidal": {},
        "Team Magma/Aqua Hideout": {PokemonGen3.ELECTRODE},
        "Terra Cave": {},
        "Trainer Hill": {},
        "Verdanturf Town": {},
        "Victory Road": {PokemonGen3.GOLBAT, PokemonGen3.HARIYAMA, PokemonGen3.ZUBAT, PokemonGen3.LOUDRED, PokemonGen3.MAKUHITA, PokemonGen3.LAIRON, PokemonGen3.WHISMUR, PokemonGen3.ARON, PokemonGen3.MEDICHAM, PokemonGen3.MEDITITE, PokemonGen3.GRAVELER, PokemonGen3.GEODUDE, PokemonGen3.BARBOACH, PokemonGen3.WHISCASH, PokemonGen3.GOLDEEN, PokemonGen3.MAWILE},
    }
)

SAPPHIRE = _BaseRSGame(
    name="Sapphire",
    encounters={
        "Route 101": {PokemonGen3.ZIGZAGOON, PokemonGen3.WURMPLE, PokemonGen3.POOCHYENA},
        "Route 102": {PokemonGen3.ZIGZAGOON, PokemonGen3.WURMPLE, PokemonGen3.POOCHYENA, PokemonGen3.RALTS, PokemonGen3.SURSKIT, PokemonGen3.LOTAD, PokemonGen3.MARILL, PokemonGen3.MAGIKARP, PokemonGen3.GOLDEEN, PokemonGen3.CORPHISH},
        "Route 103": {PokemonGen3.POOCHYENA, PokemonGen3.ZIGZAGOON, PokemonGen3.WINGULL, PokemonGen3.TENTACOOL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 104": {PokemonGen3.ZIGZAGOON, PokemonGen3.WURMPLE, PokemonGen3.TAILLOW, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.MAGIKARP},
        "Route 105": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP, PokemonGen3.REGICE},
        "Route 106": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 107": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 108": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 109": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 110": {PokemonGen3.ELECTRIKE, PokemonGen3.WINGULL, PokemonGen3.ODDISH, PokemonGen3.ZIGZAGOON, PokemonGen3.MINUN, PokemonGen3.PLUSLE, PokemonGen3.GULPIN, PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 111": {PokemonGen3.SANDSHREW, PokemonGen3.TRAPINCH, PokemonGen3.CACNEA, PokemonGen3.BALTOY, PokemonGen3.MARILL, PokemonGen3.SURSKIT, PokemonGen3.BARBOACH, PokemonGen3.MAGIKARP, PokemonGen3.GOLDEEN, PokemonGen3.GEODUDE, PokemonGen3.REGIROCK},
        "Route 112": {PokemonGen3.MACHOP, PokemonGen3.NUMEL},
        "Route 113": {PokemonGen3.SANDSHREW, PokemonGen3.SPINDA, PokemonGen3.SKARMORY},
        "Route 114": {PokemonGen3.SWABLU, PokemonGen3.SURSKIT, PokemonGen3.MARILL, PokemonGen3.BARBOACH, PokemonGen3.MAGIKARP, PokemonGen3.GOLDEEN, PokemonGen3.GEODUDE, PokemonGen3.LOTAD, PokemonGen3.LOMBRE, PokemonGen3.SEVIPER},
        "Route 115": {PokemonGen3.TAILLOW, PokemonGen3.SWABLU, PokemonGen3.JIGGLYPUFF, PokemonGen3.SWELLOW, PokemonGen3.WINGULL, PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 116": {PokemonGen3.ZIGZAGOON, PokemonGen3.WHISMUR, PokemonGen3.SKITTY, PokemonGen3.TAILLOW, PokemonGen3.NINCADA},
        "Route 117": {PokemonGen3.ZIGZAGOON, PokemonGen3.ROSELIA, PokemonGen3.SURSKIT, PokemonGen3.ODDISH, PokemonGen3.MARILL, PokemonGen3.SURSKIT, PokemonGen3.CORPHISH, PokemonGen3.MAGIKARP, PokemonGen3.ILLUMISE, PokemonGen3.VOLBEAT},
        "Route 118": {PokemonGen3.ZIGZAGOON, PokemonGen3.ELECTRIKE, PokemonGen3.KECLEON, PokemonGen3.LINOONE, PokemonGen3.WINGULL, PokemonGen3.MANECTRIC, PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.CARVANHA, PokemonGen3.SHARPEDO, PokemonGen3.GOLDEEN, PokemonGen3.MAGIKARP},
        "Route 119": {PokemonGen3.ODDISH, PokemonGen3.ZIGZAGOON, PokemonGen3.LINOONE, PokemonGen3.KECLEON, PokemonGen3.TROPIUS, PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.FEEBAS, PokemonGen3.CARVANHA, PokemonGen3.MAGIKARP},
        "Weather Institute": {PokemonGen3.CASTFORM},
        "Route 120": {PokemonGen3.ODDISH, PokemonGen3.LINOONE, PokemonGen3.SURSKIT, PokemonGen3.KECLEON, PokemonGen3.ABSOL, PokemonGen3.MARILL, PokemonGen3.ZIGZAGOON, PokemonGen3.MARILL, PokemonGen3.SURSKIT, PokemonGen3.BARBOACH, PokemonGen3.MAGIKARP, PokemonGen3.GOLDEEN, PokemonGen3.REGISTEEL},
        "Route 121": {PokemonGen3.GLOOM, PokemonGen3.WINGULL, PokemonGen3.KECLEON, PokemonGen3.ODDISH, PokemonGen3.ZIGZAGOON, PokemonGen3.LINOONE, PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP, PokemonGen3.SHUPPET},
        "Route 122": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 123": {PokemonGen3.GLOOM, PokemonGen3.WINGULL, PokemonGen3.KECLEON, PokemonGen3.ODDISH, PokemonGen3.ZIGZAGOON, PokemonGen3.LINOONE, PokemonGen3.TENTACOOL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP, PokemonGen3.SHUPPET},
        "Route 124": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP, PokemonGen3.CLAMPERL, PokemonGen3.CHINCHOU, PokemonGen3.RELICANTH},
        "Route 125": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 126": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP, PokemonGen3.CLAMPERL, PokemonGen3.CHINCHOU, PokemonGen3.RELICANTH},
        "Route 127": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 128": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.LUVDISC, PokemonGen3.CORSOLA, PokemonGen3.MAGIKARP},
        "Route 129": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILORD, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 130": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 131": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 132": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.HORSEA},
        "Route 133": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.HORSEA},
        "Route 134": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.HORSEA},
        "Abandoned Ship": {PokemonGen3.TENTACOOL, PokemonGen3.TENTACRUEL, PokemonGen3.MAGIKARP},
        "Altering Cave": {},
        "Artisan Cave": {},
        "Battle Frontier": {},
        "Battle Resort": {},
        "Battle Tower": {},
        "Birth Island": {},
        "Cave of Origin": {PokemonGen3.ZUBAT, PokemonGen3.GOLDEEN, PokemonGen3.SABLEYE, PokemonGen3.KYOGRE},
        "Desert Underpass": {},
        "Dewford Town": {PokemonGen3.WAILMER, PokemonGen3.MAGIKARP, PokemonGen3.TENTACOOL},
        "Ever Grande City": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.LUVDISC, PokemonGen3.CORSOLA, PokemonGen3.MAGIKARP},
        "Fallarbor Town": {},
        "Faraway Island": {},
        "Fiery Path": {PokemonGen3.GRIMER, PokemonGen3.KOFFING, PokemonGen3.NUMEL, PokemonGen3.MACHOP, PokemonGen3.SLUGMA, PokemonGen3.TORKOAL},
        "Fortree City": {PokemonGen3.SKITTY, PokemonGen3.PLUSLE},
        "Granite Cave": {PokemonGen3.ZUBAT, PokemonGen3.MAKUHITA, PokemonGen3.ABRA, PokemonGen3.GEODUDE, PokemonGen3.ARON, PokemonGen3.NOSEPASS, PokemonGen3.SABLEYE},
        "Jagged Pass": {PokemonGen3.MACHOP, PokemonGen3.NUMEL, PokemonGen3.SPOINK},
        "Lavaridge Town": {},
        "Lilycove City": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.STARYU, PokemonGen3.MAGIKARP},
        "Littleroot Town": {},
        "Marine Cave": {},
        "Mauville City": {},
        "Meteor Falls": {PokemonGen3.ZUBAT, PokemonGen3.GOLBAT, PokemonGen3.BARBOACH, PokemonGen3.MAGIKARP, PokemonGen3.GOLDEEN, PokemonGen3.WHISCASH, PokemonGen3.BAGON, PokemonGen3.LUNATONE},
        "Mirage Island": {PokemonGen3.WYNAUT},
        "Mirage Spots": {},
        "Mirage Tower": {},
        "Mossdeep City": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP, PokemonGen3.BELDUM},
        "Mt. Chimney": {},
        "Mt. Pyre": {PokemonGen3.DUSKULL, PokemonGen3.SHUPPET, PokemonGen3.MEDITITE, PokemonGen3.VULPIX, PokemonGen3.WINGULL, PokemonGen3.CHIMECHO},
        "New Mauville": {PokemonGen3.MAGNEMITE, PokemonGen3.VOLTORB, PokemonGen3.MAGNETON, PokemonGen3.ELECTRODE},
        "Oldale Town": {},
        "Pacifidlog Town": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP, PokemonGen3.CORSOLA},
        "Petalburg City": {PokemonGen3.MARILL, PokemonGen3.CORPHISH, PokemonGen3.MAGIKARP, PokemonGen3.GOLDEEN},
        "Petalburg Woods": {PokemonGen3.ZIGZAGOON, PokemonGen3.WURMPLE, PokemonGen3.TAILLOW, PokemonGen3.SLAKOTH, PokemonGen3.SILCOON, PokemonGen3.CASCOON, PokemonGen3.SHROOMISH},
        "Roaming Hoenn": {PokemonGen3.LATIAS},
        "Rustboro City": {PokemonGen3.MAKUHITA},
        "Rusturf Tunnel": {PokemonGen3.WHISMUR},
        "Safari Zone": {PokemonGen3.ODDISH, PokemonGen3.PHANPY, PokemonGen3.XATU, PokemonGen3.HERACROSS, PokemonGen3.GLOOM, PokemonGen3.NATU, PokemonGen3.GEODUDE, PokemonGen3.RHYHORN, PokemonGen3.DODRIO, PokemonGen3.PINSIR, PokemonGen3.DODUO, PokemonGen3.PSYDUCK, PokemonGen3.GOLDUCK, PokemonGen3.GOLDEEN, PokemonGen3.SEAKING, PokemonGen3.MAGIKARP, PokemonGen3.PIKACHU, PokemonGen3.WOBBUFFET, PokemonGen3.GIRAFARIG},
        "Scorched Slab": {},
        "Sea Mauville": {},
        "Seafloor Cavern": {PokemonGen3.ZUBAT, PokemonGen3.GOLBAT, PokemonGen3.TENTACOOL, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Sealed Chamber": {},
        "Shoal Cave": {PokemonGen3.ZUBAT, PokemonGen3.SPHEAL, PokemonGen3.GOLBAT, PokemonGen3.TENTACOOL, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP, PokemonGen3.SNORUNT},
        "Sky Pillar": {PokemonGen3.GOLBAT, PokemonGen3.CLAYDOL, PokemonGen3.ALTARIA, PokemonGen3.RAYQUAZA, PokemonGen3.BANETTE, PokemonGen3.SABLEYE},
        "Slateport City": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Sootopolis City": {PokemonGen3.MAGIKARP, PokemonGen3.GYARADOS, PokemonGen3.TENTACOOL},
        "Southern Island": {PokemonGen3.LATIOS},
        "SS Tidal": {},
        "Team Magma/Aqua Hideout": {PokemonGen3.ELECTRODE},
        "Terra Cave": {},
        "Trainer Hill": {},
        "Verdanturf Town": {},
        "Victory Road": {PokemonGen3.GOLBAT, PokemonGen3.HARIYAMA, PokemonGen3.ZUBAT, PokemonGen3.LOUDRED, PokemonGen3.MAKUHITA, PokemonGen3.LAIRON, PokemonGen3.WHISMUR, PokemonGen3.ARON, PokemonGen3.MEDICHAM, PokemonGen3.MEDITITE, PokemonGen3.GRAVELER, PokemonGen3.GEODUDE, PokemonGen3.BARBOACH, PokemonGen3.WHISCASH, PokemonGen3.GOLDEEN},
    }
)

EMERALD = _BaseRSGame(
    name="Emerald",
    gyms=[
        GymTrainer(
            leader="Roxanne",
            type=Types.ROCK,
            pokemons=[
                TrainerPokemon(PokemonGen3.GEODUDE, 12),
                TrainerPokemon(PokemonGen3.GEODUDE, 12),
                TrainerPokemon(PokemonGen3.NOSEPASS, 15),
            ],
            location="Rustboro City",
            badge="Stone Badge"
        ),
        GymTrainer(
            leader="Brawly",
            type=Types.FIGHTING,
            pokemons=[
                TrainerPokemon(PokemonGen3.MACHOP, 16),
                TrainerPokemon(PokemonGen3.MEDITITE, 16),
                TrainerPokemon(PokemonGen3.MAKUHITA, 19),
            ],
            location="Dewford Town",
            badge="Knuckle Badge"
        ),
        GymTrainer(
            leader="Wattson",
            type=Types.ELECTRIC,
            pokemons=[
                TrainerPokemon(PokemonGen3.VOLTORB, 20),
                TrainerPokemon(PokemonGen3.MAGNETON, 22),
                TrainerPokemon(PokemonGen3.ELECTRIKE, 20),
                TrainerPokemon(PokemonGen3.MANECTRIC, 24),
            ],
            location="Mauville City",
            badge="Dynamo Badge"
        ),
        GymTrainer(
            leader="Flannery",
            type=Types.FIRE,
            pokemons=[
                TrainerPokemon(PokemonGen3.NUMEL, 24),
                TrainerPokemon(PokemonGen3.SLUGMA, 24),
                TrainerPokemon(PokemonGen3.CAMERUPT, 26),
                TrainerPokemon(PokemonGen3.TORKOAL, 29),
            ],
            location="Lavaridge City",
            badge="Heat Badge"
        ),
        GymTrainer(
            leader="Norman",
            type=Types.NORMAL,
            pokemons=[
                TrainerPokemon(PokemonGen3.SPINDA, 27),
                TrainerPokemon(PokemonGen3.VIGOROTH, 27),
                TrainerPokemon(PokemonGen3.LINOONE, 29),
                TrainerPokemon(PokemonGen3.SLAKING, 31),
            ],
            location="Petalburg City",
            badge="Balance Badge"
        ),
        GymTrainer(
            leader="Winona",
            type=Types.FLYING,
            pokemons=[
                TrainerPokemon(PokemonGen3.SWABLU, 29),
                TrainerPokemon(PokemonGen3.TROPIUS, 29),
                TrainerPokemon(PokemonGen3.PELIPPER, 30),
                TrainerPokemon(PokemonGen3.SKARMORY, 31),
                TrainerPokemon(PokemonGen3.ALTARIA, 33),
            ],
            location="Fortree Town",
            badge="Feather Badge"
        ),
        GymTrainer(
            leader="Tate & Liza",
            type=Types.PSYCHIC,
            pokemons=[
                TrainerPokemon(PokemonGen3.CLAYDOL, 41),
                TrainerPokemon(PokemonGen3.XATU, 41),
                TrainerPokemon(PokemonGen3.SOLROCK, 42),
                TrainerPokemon(PokemonGen3.LUNATONE, 42),
            ],
            location="Mossdeep City",
            badge="Mind Badge"
        ),
        GymTrainer(
            leader="Juan",
            type=Types.FIGHTING,
            pokemons=[
                TrainerPokemon(PokemonGen3.LUVDISC, 41),
                TrainerPokemon(PokemonGen3.WHISCASH, 41),
                TrainerPokemon(PokemonGen3.SEALEO, 43),
                TrainerPokemon(PokemonGen3.CRAWDAUNT, 43),
                TrainerPokemon(PokemonGen3.KINGDRA, 46),
            ],
            location="Sootopolis City",
            badge="Rain Badge"
        ),
    ],
    elite4=[
        EliteTrainer(
            leader="Sydney", type=Types.DARK, pokemons=[
                TrainerPokemon(PokemonGen3.MIGHTYENA, 46),
                TrainerPokemon(PokemonGen3.CACTURNE, 46),
                TrainerPokemon(PokemonGen3.SHIFTRY, 48),
                TrainerPokemon(PokemonGen3.CRAWDAUNT, 48),
                TrainerPokemon(PokemonGen3.ABSOL, 49),
            ]
        ),
        EliteTrainer(
            leader="Phoebe", type=Types.GHOST, pokemons=[
                TrainerPokemon(PokemonGen3.DUSCLOPS, 48),
                TrainerPokemon(PokemonGen3.BANETTE, 49),
                TrainerPokemon(PokemonGen3.BANETTE, 49),
                TrainerPokemon(PokemonGen3.SABLEYE, 50),
                TrainerPokemon(PokemonGen3.DUSCLOPS, 51),
            ]
        ),
        EliteTrainer(
            leader="Glacia", type=Types.ICE, pokemons=[
                TrainerPokemon(PokemonGen3.GLALIE, 50),
                TrainerPokemon(PokemonGen3.SEALEO, 50),
                TrainerPokemon(PokemonGen3.GLALIE, 52),
                TrainerPokemon(PokemonGen3.SEALEO, 52),
                TrainerPokemon(PokemonGen3.WALREIN, 53),
            ]
        ),
        EliteTrainer(
            leader="Drake", type=Types.DRAGON, pokemons=[
                TrainerPokemon(PokemonGen3.SHELGON, 52),
                TrainerPokemon(PokemonGen3.ALTARIA, 54),
                TrainerPokemon(PokemonGen3.KINGDRA, 53),
                TrainerPokemon(PokemonGen3.FLYGON, 53),
                TrainerPokemon(PokemonGen3.SALAMENCE, 55),
            ]
        ),
        EliteTrainer(
            leader="Wallace", type=Types.WATER, pokemons=[
                TrainerPokemon(PokemonGen3.WAILMER, 57),
                TrainerPokemon(PokemonGen3.TENTACRUEL, 55),
                TrainerPokemon(PokemonGen3.WHISCASH, 56),
                TrainerPokemon(PokemonGen3.LUDICOLO, 56),
                TrainerPokemon(PokemonGen3.GYARADOS, 56),
                TrainerPokemon(PokemonGen3.MILTOIC, 58),
            ]
        ),
    ],
    important_battles=[
        "Rustboro City - GymTrainer (15)",
        "Rustboro City - Rival (15)",
        "Dewford Town - GymTrainer (19)",
        "Route 110 - Rival (20)",
        "Mauville City - Wally (16)",
        "Mauville City - GymTrainer (24)",
        "Mt. Chimney - Boss (25)",
        "Lavaridge City - GymTrainer (29)",
        "Petalburg City - GymTrainer (31)",
        "Weather Institute - Boss (28)"
        "Route 119 - Rival (31)",
        "Fortree Town - GymTrainer (33)",
        "Lilycove City - Rival (34)",
        "Jagged Pass - Boss (39)"
        "Team X Hideout - Boss (34)",
        "Mossdeep City - GymTrainer (42)",
        "Space Center - Boss (40)",
        "Route 128 - Boss (43)",
        "Sootopolis City - GymTrainer (46)",
        "Ever Grand City - Wally (45)",
        "EliteTrainer 4  (58)",
    ],
    encounters={
        "Route 101": {PokemonGen3.ZIGZAGOON, PokemonGen3.WURMPLE, PokemonGen3.POOCHYENA},
        "Route 102": {PokemonGen3.WURMPLE, PokemonGen3.POOCHYENA, PokemonGen3.RALTS, PokemonGen3.SEEDOT, PokemonGen3.LOTAD, PokemonGen3.ZIGZAGOON, PokemonGen3.MARILL, PokemonGen3.GOLDEEN, PokemonGen3.CORPHISH, PokemonGen3.MAGIKARP},
        "Route 103": {PokemonGen3.POOCHYENA, PokemonGen3.ZIGZAGOON, PokemonGen3.WINGULL, PokemonGen3.TENTACOOL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 104": {PokemonGen3.POOCHYENA, PokemonGen3.TAILLOW, PokemonGen3.MARILL, PokemonGen3.WURMPLE, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.MAGIKARP},
        "Route 105": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP, PokemonGen3.REGICE},
        "Route 106": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 107": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 108": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 109": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 110": {PokemonGen3.ELECTRIKE, PokemonGen3.WINGULL, PokemonGen3.PLUSLE, PokemonGen3.ODDISH, PokemonGen3.MINUN, PokemonGen3.GULPIN, PokemonGen3.POOCHYENA, PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 111": {PokemonGen3.SANDSHREW, PokemonGen3.TRAPINCH, PokemonGen3.CACNEA, PokemonGen3.BALTOY, PokemonGen3.MARILL, PokemonGen3.BARBOACH, PokemonGen3.MAGIKARP, PokemonGen3.GOLDEEN, PokemonGen3.GEODUDE, PokemonGen3.REGIROCK},
        "Route 112": {PokemonGen3.MARILL, PokemonGen3.NUMEL},
        "Route 113": {PokemonGen3.SLUGMA, PokemonGen3.SPINDA, PokemonGen3.SKARMORY},
        "Route 114": {PokemonGen3.LOTAD, PokemonGen3.SWABLU, PokemonGen3.NUZLEAF, PokemonGen3.SEVIPER, PokemonGen3.LOMBRE, PokemonGen3.MARILL, PokemonGen3.GOLDEEN, PokemonGen3.BARBOACH, PokemonGen3.MAGIKARP, PokemonGen3.GEODUDE},
        "Route 115": {PokemonGen3.TAILLOW, PokemonGen3.SWABLU, PokemonGen3.JIGGLYPUFF, PokemonGen3.SWELLOW, PokemonGen3.WINGULL, PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 116": {PokemonGen3.POOCHYENA, PokemonGen3.SKITTY, PokemonGen3.TAILLOW, PokemonGen3.NINCADA, PokemonGen3.ABRA, PokemonGen3.WHISMUR},
        "Route 117": {PokemonGen3.ODDISH, PokemonGen3.POOCHYENA, PokemonGen3.VOLBEAT, PokemonGen3.SEEDOT, PokemonGen3.MARILL, PokemonGen3.ILLUMISE, PokemonGen3.GOLDEEN, PokemonGen3.CORPHISH, PokemonGen3.MAGIKARP},
        "Route 118": {PokemonGen3.ZIGZAGOON, PokemonGen3.ELECTRIKE, PokemonGen3.KECLEON, PokemonGen3.LINOONE, PokemonGen3.WINGULL, PokemonGen3.MANECTRIC, PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.CARVANHA, PokemonGen3.SHARPEDO, PokemonGen3.GOLDEEN, PokemonGen3.MAGIKARP},
        "Route 119": {PokemonGen3.ODDISH, PokemonGen3.ZIGZAGOON, PokemonGen3.LINOONE, PokemonGen3.KECLEON, PokemonGen3.TROPIUS, PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.FEEBAS, PokemonGen3.CARVANHA, PokemonGen3.MAGIKARP},
        "Weather Institute": {PokemonGen3.CASTFORM},
        "Route 120": {PokemonGen3.ODDISH, PokemonGen3.MIGHTYENA, PokemonGen3.KECLEON, PokemonGen3.ABSOL, PokemonGen3.SEEDOT, PokemonGen3.MARILL, PokemonGen3.POOCHYENA, PokemonGen3. GOLDEEN, PokemonGen3.BARBOACH, PokemonGen3.MAGIKARP, PokemonGen3.REGISTEEL},
        "Route 121": {PokemonGen3.SHUPPET, PokemonGen3.GLOOM, PokemonGen3.WINGULL, PokemonGen3.KECLEON, PokemonGen3.ODDISH, PokemonGen3.POOCHYENA, PokemonGen3.MIGHTYENA,   PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 122": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 123": {PokemonGen3.GLOOM, PokemonGen3.WINGULL, PokemonGen3.KECLEON, PokemonGen3.ODDISH, PokemonGen3.POOCHYENA, PokemonGen3.MIGHTYENA, PokemonGen3.TENTACOOL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP, PokemonGen3.SHUPPET},
        "Route 124": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP, PokemonGen3.CLAMPERL, PokemonGen3.CHINCHOU, PokemonGen3.RELICANTH},
        "Route 125": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 126": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP, PokemonGen3.CLAMPERL, PokemonGen3.CHINCHOU, PokemonGen3.RELICANTH},
        "Route 127": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 128": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.LUVDISC, PokemonGen3.CORSOLA, PokemonGen3.MAGIKARP},
        "Route 129": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILORD, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 130": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 131": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Route 132": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.HORSEA},
        "Route 133": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.HORSEA},
        "Route 134": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.HORSEA},
        "Abandoned Ship": {PokemonGen3.TENTACOOL, PokemonGen3.TENTACRUEL, PokemonGen3.MAGIKARP},
        "Altering Cave": {PokemonGen3.ZUBAT, PokemonGen3.MAREEP, PokemonGen3.AIPOM, PokemonGen3.PINECO, PokemonGen3.SHUCKLE, PokemonGen3.TEDDIURSA, PokemonGen3.HOUNDOUR, PokemonGen3.STANTLER, PokemonGen3.SMEARGLE},
        "Artisan Cave": {PokemonGen3.SMEARGLE},
        "Battle Frontier": {},
        "Battle Resort": {},
        "Battle Tower": {PokemonGen3.MEOWTH},
        "Birth Island": {PokemonGen3.DEOXYS},
        "Cave of Origin": {PokemonGen3.ZUBAT, PokemonGen3.GOLDEEN, PokemonGen3.SABLEYE},
        "Desert Underpass": {PokemonGen3.DITTO, PokemonGen3.WHISMUR, PokemonGen3.LOUDRED},
        "Dewford Town": {PokemonGen3.WAILMER, PokemonGen3.MAGIKARP, PokemonGen3.TENTACOOL},
        "Ever Grande City": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.LUVDISC, PokemonGen3.CORSOLA, PokemonGen3.MAGIKARP},
        "Fallarbor Town": {},
        "Faraway Island": {PokemonGen3.MEW},
        "Fiery Path": {PokemonGen3.GRIMER, PokemonGen3.KOFFING, PokemonGen3.NUMEL, PokemonGen3.MACHOP, PokemonGen3.SLUGMA, PokemonGen3.TORKOAL},
        "Fortree City": {},
        "Granite Cave": {PokemonGen3.ZUBAT, PokemonGen3.MAKUHITA, PokemonGen3.ABRA, PokemonGen3.GEODUDE, PokemonGen3.ARON, PokemonGen3.NOSEPASS, PokemonGen3.SABLEYE},
        "Jagged Pass": {PokemonGen3.MACHOP, PokemonGen3.NUMEL, PokemonGen3.SPOINK},
        "Lavaridge Town": {},
        "Lilycove City": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.STARYU, PokemonGen3.MAGIKARP},
        "Littleroot Town": {PokemonGen3.CHIKORITA, PokemonGen3.CYNDAQUIL, PokemonGen3.TOTODILE},
        "Marine Cave": {PokemonGen3.KYOGRE},
        "Mauville City": {},
        "Meteor Falls": {PokemonGen3.ZUBAT, PokemonGen3.GOLBAT, PokemonGen3.BARBOACH, PokemonGen3.MAGIKARP, PokemonGen3.GOLDEEN, PokemonGen3.WHISCASH, PokemonGen3.BAGON, PokemonGen3.SOLROCK},
        "Mirage Island": {PokemonGen3.WYNAUT},
        "Mirage Spots": {},
        "Mirage Tower": {PokemonGen3.SANDSHREW, PokemonGen3.TRAPINCH},
        "Mossdeep City": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP, PokemonGen3.BELDUM},
        "Mt. Chimney": {},
        "Mt. Pyre": {PokemonGen3.DUSKULL, PokemonGen3.SHUPPET, PokemonGen3.VULPIX, PokemonGen3.WINGULL, PokemonGen3.CHIMECHO},
        "New Mauville": {PokemonGen3.MAGNEMITE, PokemonGen3.VOLTORB, PokemonGen3.MAGNETON, PokemonGen3.ELECTRODE},
        "Oldale Town": {},
        "Pacifidlog Town": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.SHARPEDO, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP, PokemonGen3.HORSEA},
        "Petalburg City": {PokemonGen3.MARILL, PokemonGen3.CORPHISH, PokemonGen3.MAGIKARP, PokemonGen3.GOLDEEN},
        "Petalburg Woods": {PokemonGen3.POOCHYENA, PokemonGen3.WURMPLE, PokemonGen3.TAILLOW, PokemonGen3.SLAKOTH, PokemonGen3.SILCOON, PokemonGen3.CASCOON, PokemonGen3.SHROOMISH},
        "Roaming Hoenn": {PokemonGen3.LATIAS, PokemonGen3.LATIOS},
        "Rustboro City": {PokemonGen3.SEEDOT},
        "Rusturf Tunnel": {PokemonGen3.WHISMUR},
        "Safari Zone": {PokemonGen3.AIPOM, PokemonGen3.TEDDIURSA, PokemonGen3.HOOTHOOT, PokemonGen3.PINECO, PokemonGen3.HOUNDOUR, PokemonGen3.MILTANK, PokemonGen3.LEDYBA, PokemonGen3.SUNKERN, PokemonGen3.SHUCKLE, PokemonGen3.ODDISH, PokemonGen3.PHANPY, PokemonGen3.XATU, PokemonGen3.HERACROSS, PokemonGen3.GLOOM, PokemonGen3.NATU, PokemonGen3.GEODUDE, PokemonGen3.RHYHORN, PokemonGen3.DODRIO, PokemonGen3.PINSIR, PokemonGen3.DODUO, PokemonGen3.PSYDUCK, PokemonGen3.GOLDUCK, PokemonGen3.GOLDEEN, PokemonGen3.SEAKING, PokemonGen3.MAGIKARP, PokemonGen3.MAREEP, PokemonGen3.GLIGAR, PokemonGen3.SNUBBULL, PokemonGen3.STANTLER, PokemonGen3.SPINARAK, PokemonGen3.MARILL, PokemonGen3.WOOPER, PokemonGen3.QUAGSIRE, PokemonGen3.REMORAID, PokemonGen3.OCTILLERY, PokemonGen3.PIKACHU, PokemonGen3.WOBBUFFET},
        "Scorched Slab": {},
        "Sea Mauville": {},
        "Seafloor Cavern": {PokemonGen3.ZUBAT, PokemonGen3.GOLBAT, PokemonGen3.TENTACOOL, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Sealed Chamber": {},
        "Shoal Cave": {PokemonGen3.ZUBAT, PokemonGen3.SPHEAL, PokemonGen3.GOLBAT, PokemonGen3.TENTACOOL, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP, PokemonGen3.SNORUNT},
        "Sky Pillar": {PokemonGen3.GOLBAT, PokemonGen3.CLAYDOL, PokemonGen3.ALTARIA, PokemonGen3.RAYQUAZA, PokemonGen3.BANETTE, PokemonGen3.SABLEYE},
        "Slateport City": {PokemonGen3.TENTACOOL, PokemonGen3.WINGULL, PokemonGen3.PELIPPER, PokemonGen3.WAILMER, PokemonGen3.MAGIKARP},
        "Sootopolis City": {PokemonGen3.MAGIKARP, PokemonGen3.GYARADOS, PokemonGen3.TENTACOOL},
        "Southern Island": {PokemonGen3.LATIOS, PokemonGen3.LATIAS},
        "SS Tidal": {},
        "Team Magma/Aqua Hideout": {PokemonGen3.ELECTRODE, PokemonGen3.GEODUDE, PokemonGen3.TORKOAL, PokemonGen3.GRAVELER},
        "Terra Cave": {PokemonGen3.GROUDON},
        "Trainer Hill": {},
        "Verdanturf Town": {},
        "Victory Road": {PokemonGen3.GOLBAT, PokemonGen3.HARIYAMA, PokemonGen3.ZUBAT, PokemonGen3.LOUDRED, PokemonGen3.MAKUHITA, PokemonGen3.LAIRON, PokemonGen3.WHISMUR, PokemonGen3.ARON, PokemonGen3.MEDICHAM, PokemonGen3.MEDITITE, PokemonGen3.GRAVELER, PokemonGen3.GEODUDE, PokemonGen3.BARBOACH, PokemonGen3.WHISCASH, PokemonGen3.GOLDEEN, PokemonGen3.MAWILE},
    },
)
