from definitions import Game, GymTrainer, TrainerPokemon, EliteTrainer
from pokemendel_core.utils.definitions import Regions, Types
from pokemendel_core.data import fetch_pokemon
from pokemendel_core.data.gen4 import PokemonGen4
from dataclasses import dataclass


_GENERATION = 4


@dataclass
class _BaseGen4Game(Game):
    def __init__(self, **kwargs):
        assert 'name' in kwargs
        for override_field, default_value in [
            ('gen', _GENERATION),
            ('region', Regions.SINNOH),
            ('gyms', [
        GymTrainer(
            leader="Roark",
            type=Types.ROCK,
            pokemons=[
                TrainerPokemon(PokemonGen4.GEODUDE, 12),
                TrainerPokemon(PokemonGen4.ONIX, 12),
                TrainerPokemon(PokemonGen4.CRANIDOS, 14),
            ],
            location="Oreburgh City",
            badge="Coal Badge"
        ),
        GymTrainer(
            leader="Gardenia",
            type=Types.GRASS,
            pokemons=[
                TrainerPokemon(PokemonGen4.CHERUBI, 19),
                TrainerPokemon(PokemonGen4.TURTWIG, 19),
                TrainerPokemon(PokemonGen4.ROSERADE, 22),
            ],
            location="Eterna City",
            badge="Forest Badge"
        ),
        GymTrainer(
            leader="Maylene",
            type=Types.FIGHTING,
            pokemons=[
                TrainerPokemon(PokemonGen4.MEDITITE, 27),
                TrainerPokemon(PokemonGen4.MACHOKE, 27),
                TrainerPokemon(PokemonGen4.LUCARIO, 30),
            ],
            location="Veilstone City",
            badge="Cobal Badge"
        ),
        GymTrainer(
            leader="Crasher Wake",
            type=Types.WATER,
            pokemons=[
                TrainerPokemon(PokemonGen4.GYARADOS, 27),
                TrainerPokemon(PokemonGen4.QUAGSIRE, 27),
                TrainerPokemon(PokemonGen4.FLOATZEL, 30),
            ],
            location="Pastoria City",
            badge="Fen Badge"
        ),
        GymTrainer(
            leader="Fantina",
            type=Types.GHOST,
            pokemons=[
                TrainerPokemon(PokemonGen4.DRIFBLIM, 32),
                TrainerPokemon(PokemonGen4.GENGAR, 34),
                TrainerPokemon(PokemonGen4.MISMAGIUS, 36),
            ],
            location="Hearthome City",
            badge="Relic Badge"
        ),
        GymTrainer(
            leader="Byron",
            type=Types.STEEL,
            pokemons=[
                TrainerPokemon(PokemonGen4.BRONZOR, 36),
                TrainerPokemon(PokemonGen4.STEELIX, 36),
                TrainerPokemon(PokemonGen4.BASTIODON, 39),
            ],
            location="Canalave City",
            badge="Mine Badge"
        ),
        GymTrainer(
            leader="Candice",
            type=Types.ICE,
            pokemons=[
                TrainerPokemon(PokemonGen4.SNOVER, 38),
                TrainerPokemon(PokemonGen4.SNEASEL, 38),
                TrainerPokemon(PokemonGen4.MEDICHAM, 40),
                TrainerPokemon(PokemonGen4.ABOMASNOW, 42),
            ],
            location="Snowpoint City",
            badge="Icicle Badge"
        ),
        GymTrainer(
            leader="Volkner",
            type=Types.ELECTRIC,
            pokemons=[
                TrainerPokemon(PokemonGen4.RAICHU, 46),
                TrainerPokemon(PokemonGen4.AMBIPOM, 47),
                TrainerPokemon(PokemonGen4.OCTILLERY, 48),
                TrainerPokemon(PokemonGen4.LUXRAY, 49),
            ],
            location="Sunyshore City",
            badge="Beacon Badge"
        ),
    ]),
            ('elite4', [
        EliteTrainer(
            leader="Aaron", type=Types.BUG, pokemons=[
                TrainerPokemon(PokemonGen4.DUSTOX, 53),
                TrainerPokemon(PokemonGen4.BEAUTIFLY, 53),
                TrainerPokemon(PokemonGen4.HERACROSS, 54),
                TrainerPokemon(PokemonGen4.VESPIQUEN, 54),
                TrainerPokemon(PokemonGen4.DRAPION, 57),
            ]
        ),
        EliteTrainer(
            leader="Bertha", type=Types.GROUND, pokemons=[
                TrainerPokemon(PokemonGen4.QUAGSIRE, 55),
                TrainerPokemon(PokemonGen4.WHISCASH, 55),
                TrainerPokemon(PokemonGen4.GOLEM, 56),
                TrainerPokemon(PokemonGen4.SUDOWOODO, 57),
                TrainerPokemon(PokemonGen4.HIPPOWDON, 59),
            ]
        ),
        EliteTrainer(
            leader="Flint", type=Types.FIRE, pokemons=[
                TrainerPokemon(PokemonGen4.RAPIDASH, 58),
                TrainerPokemon(PokemonGen4.STEELIX, 57),
                TrainerPokemon(PokemonGen4.LOPUNNY, 57),
                TrainerPokemon(PokemonGen4.DRIFBLIM, 58),
                TrainerPokemon(PokemonGen4.INFERNAPE, 61),
            ]
        ),
        EliteTrainer(
            leader="Lucian", type=Types.PSYCHIC, pokemons=[
                TrainerPokemon(PokemonGen4.MR_MIME, 59),
                TrainerPokemon(PokemonGen4.GIRAFARIG, 59),
                TrainerPokemon(PokemonGen4.MEDICHAM, 60),
                TrainerPokemon(PokemonGen4.ALAKAZAM, 60),
                TrainerPokemon(PokemonGen4.BRONZONG, 63),
            ]
        ),
    ]),
            ('routes', [
               "Twinleaf Town",
               "Verity Lakefront",
               "Verity Lakefront",
               "Sandgem Town",
               "Jubilife City",
               "Oreburgh Gate",
               "Oreburgh City"
               "Oreburgh Mine",
               "Ravaged Path",
               "Floaroma Town",
               "Valley Windworks",
               "Eterna Forest",
               "Old Chateau",
               "Eterna City",
               "Wayward Cave",
               "Mt. Coronet",
               "Hearthome City",
               "Hallowed Tower",
               "Lost Tower",
               "Solaceon Town",
               "Solaceon Ruins",
               "Veilstone City",
               "Café Cabin",
               "Galactic Warehouse",
               "Ruin Maniac Cave",
               "Valor Lakefront",
               "Pastoria City",
               "Great Marsh",
               "Pokémon Mansion",
               "Trophy Garden",
               "Celestic Town",
               "Celestic Ruins",
               "Canalave City",
               "Iron Island",
               "Lake Valor",
               "Valor Cavern",
               "Acuity Lakefront",
               "Snowpoint City",
               "Lake Acuity",
               "Team Galactic HQ",
               "Sunyshore City",
               "Pokémon League",
               "Victory Road",
               "Route 201", 
               "Route 202",
               "Route 203",
               "Route 204",
               "Route 205",
               "Route 206",
               "Route 207",
               "Route 208",
               "Route 209",
               "Route 210",
               "Route 211",
               "Route 212",
               "Route 213",
               "Route 214",
               "Route 215",
               "Route 216",
               "Route 217",
               "Route 218",
               "Route 222",
               "Route 223",
]),
            ('starters', [
        fetch_pokemon(PokemonGen4.TURTWIG, _GENERATION),
        fetch_pokemon(PokemonGen4.CHIMCHAR, _GENERATION),
        fetch_pokemon(PokemonGen4.PIPLUP, _GENERATION),
    ]),
            ('important_battles', [
                "Route 203 - Rival (9)",
                "Oreburgh City - GymTrainer (14)",
                "Valley Windworks - Boss (16)",
                "Eterna City - GymTrainer (22)",
                "Team Galactic Eterna Building - Boss (20)",
                "Hearthome City - Rival (21)"
                "Veilstone City - GymTrainer (30)",
                "Pastoria City - GymTrainer (30)",
                "Pastoria City - Rival (28)",
                "Hearthome City - GymTrainer (36)",
                "Canalave City - Rival (35)",
                "Canalave City - GymTrainer (39)",
                "Valor Cavern - Boss (39)",
                "Snowpoint City - GymTrainer (42)",
                "Team Galactic HQ - Boss (43)",
                "Team Galactic HQ - Boss (40)",
                "Team Galactic HQ - Boss (48)",
                "Sunyshore City - GymTrainer (49)",
                "Pokémon League - Boss (53)",
                "Elite 4 (63)"
            ]),
            ('egg_pokemons', {
                PokemonGen4.OMANYTE,
PokemonGen4.KABUTO,
PokemonGen4.AERODACTYL,
PokemonGen4.LILEEP,
PokemonGen4.ANORITH,
PokemonGen4.CRANIDOS,
PokemonGen4.SHIELDON,
PokemonGen4.RIOLU,
            }),
        ]:
            kwargs[override_field] = kwargs.get(override_field, default_value)
        super().__init__(**kwargs)


DIAMOND = _BaseGen4Game(
    name="Diamond",
    encounters={
        "Twinleaf Town": {
            PokemonGen4.PSYDUCK, 
            PokemonGen4.GOLDUCK,
            PokemonGen4.SEAKING,
            PokemonGen4.GYARADOS,
            PokemonGen4.GOLDEEN,
            PokemonGen4.MAGIKARP,},
"Verity Lakefront": {},
"Sandgem Town": {},
"Jubilife City": {},
"Oreburgh Gate": {
    PokemonGen4.GEODUDE,
    PokemonGen4.ZUBAT.
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLBAT,
    PokemonGen4.GOLDUCK,
    PokemonGen4.GYARADOS,
    PokemonGen4.WHISCASH,
    PokemonGen4.MAGIKARP,
    PokemonGen4.BARBOACH,
},
"Oreburgh City": {
PokemonGen4.OMANYTE,
PokemonGen4.KABUTO,
PokemonGen4.AERODACTYL,
PokemonGen4.LILEEP,
PokemonGen4.ANORITH,
PokemonGen4.CRANIDOS,
PokemonGen4.SHIELDON,
PokemonGen4.ABRA,
},
"Oreburgh Mine": {
    PokemonGen4.GEODUDE,
    PokemonGen4.ZUBAT.
    PokemonGen4.ONIX,
},
"Ravaged Path": {
    PokemonGen4.ZUBAT,
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLBAT,
    PokemonGen4.GOLDUCK,
    PokemonGen4.GYARADOS,
    PokemonGen4.WHISCASH,
    PokemonGen4.MAGIKARP,
    PokemonGen4.BARBOACH,
    PokemonGen4.GEODUDE,
},
"Floaroma Town": {},
"Valley Windworks": {
    PokemonGen4.PACHIRISU,
    PokemonGen4.BUIZEL,
    PokemonGen4.SHELLOS,
    PokemonGen4.ELEKID,
    PokemonGen4.ELECTRIKE,
    PokemonGen4.TENTACOOL,
    PokemonGen4.TENTACRUEL,
    PokemonGen4.GYARADOS,
    PokemonGen4.LUMINEON,
    PokemonGen4.SHELLDER,
    PokemonGen4.MAGIKARP,
    PokemonGen4.FINNEON,
    PokemonGen4.DRIFLOON,
    PokemonGen4.MAREEP,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.WINGULL,
    PokemonGen4.BIDOOF,
    PokemonGen4.PELIPPER,
    PokemonGen4.SILCOON,
},
"Eterna Forest": {
    PokemonGen4.WURMPLE,
    PokemonGen4.BUDEW,
    PokemonGen4.PINECO,
    PokemonGen4.METAPOD,
    PokemonGen4.KAKUNA,
    PokemonGen4.SEEDOT,
    PokemonGen4.SLAKOTH,
    PokemonGen4.NINCADA,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.BEAUTIFLY,
    PokemonGen4.MURKROW,
},
"Old Chateau": {
    PokemonGen4.GASTLY,
    PokemonGen4.ROTOM,
    PokemonGen4.GENGAR,
    PokemonGen4.HAUNTER,
},
"Eterna City": {
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.GYARADOS,
    PokemonGen4.WHISCASH,
    PokemonGen4.MAGIKARP,
    PokemonGen4.BARBOACH,
    PokemonGen4.CHATOT,
},
"Wayward Cave": {
    PokemonGen4.ZUBAT,
    PokemonGen4.BRONZOR,
    PokemonGen4.GEODUDE,
    PokemonGen4.SANDSHREW,
},
"Mt. Coronet": {
    PokemonGen4.GRAVELER,
    PokemonGen4.BRONZOR,
    PokemonGen4.GOLBAT,
    PokemonGen4.CLEFAIRY,
    PokemonGen4.MACHOKE,
    PokemonGen4.MEDICHAM,
    PokemonGen4.CHINGLING,
    PokemonGen4.BRONZONG,
    PokemonGen4.SOLROCK,
    PokemonGen4.LUNATONE,
    PokemonGen4.GYARADOS,
    PokemonGen4.DRATINI,
    PokemonGen4.DRAGONAIR,
    PokemonGen4.WHISCASH,
    PokemonGen4.MAGIKARP,
    PokemonGen4.BARBOACH,
    PokemonGen4.CHIMECHO,
    PokemonGen4.MEDITITE,
    PokemonGen4.FEEBAS,
    PokemonGen4.MACHOP,
    PokemonGen4.GEODUDE,
    PokemonGen4.CLEFFA,
    PokemonGen4.ZUBAT,
    PokemonGen4.ABOMASNOW,
    PokemonGen4.NOCTOWL,
    PokemonGen4.SNOVER,
    PokemonGen4.LOUDRED,
},
"Hearthome City": {},
"Hallowed Tower": {},
"Lost Tower": {
    PokemonGen4.ZUBAT,
    PokemonGen4.GASTLY,
    PokemonGen4.GOLBAT,
    PokemonGen4.MURKROW,
},
"Solaceon Town": {},
"Solaceon Ruins": {
    PokemonGen4.UNOWN,
},
"Veilstone City": {},
"Café Cabin": {},
"Galactic Warehouse": {},
"Ruin Maniac Cave": {
    PokemonGen4.GEODUDE,
    PokemonGen4.HIPPOPOTAS,
},
"Valor Lakefront": {
    PokemonGen4.GIRAFARIG,
    PokemonGen4.KRICKETUNE,
    PokemonGen4.STARVIA,
    PokemonGen4.BIBAREL,
    PokemonGen4.GRAVELER,
    PokemonGen4.GEODUDE,
    PokemonGen4.NIDORINA,
},
"Pastoria City": {
    PokemonGen4.TENTACOOL,
    PokemonGen4.TENTACRUEL,
    PokemonGen4.GYARADOS,
    PokemonGen4.OCTILLERY,
    PokemonGen4.MAGIKARP,
    PokemonGen4.REMORAID,
    PokemonGen4.WINGULL,
    PokemonGen4.PELIPPER,
},
"Great Marsh": {
    PokemonGen4.PSYDUCK,
    PokemonGen4.AZURILL,
    PokemonGen4.BIDOOF,
    PokemonGen4.HOOTHOOT,
    PokemonGen4.NOCTOWL,
    PokemonGen4.MARILL,
    PokemonGen4.WOOOPER,
    PokemonGen4.QUAGSIRE,
    PokemonGen4.STARLY,
    PokemonGen4.BIBAREL,
    PokemonGen4.BUDEW,
    PokemonGen4.ARBOK,
    PokemonGen4.CARVANHA,
    PokemonGen4.WHISCASH,
    PokemonGen4.GYARADOS,
    PokemonGen4.MAGIKARP,
    PokemonGen4.BARBOACH,
    PokemonGen4.PARAS,
    PokemonGen4.GOLDUCK,
    PokemonGen4.EXEGGCUTE,
    PokemonGen4.KANGASKHAN,
    PokemonGen4.SHROOMISH, 
    PokemonGen4.ROSELIA,
    PokemonGen4.GULPIN,
    PokemonGen4.STARAVIA,
    PokemonGen4.SKORUPI,
    PokemonGen4.DRAPION,
    PokemonGen4.CROAGUNK,
    PokemonGen4.TOXICROAK,
    PokemonGen4.CARNIVINE,
},
"Pokémon Mansion": {},
"Trophy Garden": {
    PokemonGen4.PICHU,
    PokemonGen4.ROSELIA,
    PokemonGen4.STARAVIA,
    PokemonGen4.KRICKETUNE,
    PokemonGen4.PIKACHU,
    PokemonGen4.CLEFAIRY,
    PokemonGen4.JIGGLYPUFF,
    PokemonGen4.MEOWTH,
    PokemonGen4.CHANSEY,
    PokemonGen4.EEVEE,
    PokemonGen4.CLEFFA,
    PokemonGen4.IGGLYBUFF,
    PokemonGen4.MARILL,
    PokemonGen4.AZURILL,
    PokemonGen4.PLUSLE,
    PokemonGen4.MINUN,
    PokemonGen4.CASTFORM,
    PokemonGen4.BONSLY,
    PokemonGen4.MIME_JR,
    PokemonGen4.HAPPINY,
    PokemonGen4.PORYGON,
},
"Celestic Town": {
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.GYARADOS,
    PokemonGen4.CORPHISH,
    PokemonGen4.CRAWDAUNT,
    PokemonGen4.MAGIKARP,
    PokemonGen4.WHISCASH,
    PokemonGen4.BARBOACH,
},
"Celestic Ruins": {},
"Canalave City": {
    PokemonGen4.TENTACOOL,
    PokemonGen4.TENTACRUEL,
    PokemonGen4.GYARADOS,
    PokemonGen4.LUMINEON,
    PokemonGen4.STARYU,
    PokemonGen4.MAGIKARP,
    PokemonGen4.FINNEON,
    PokemonGen4.WINGULL,
    PokemonGen4.PELIPPER,
},
"Iron Island": {
    PokemonGen4.GEODUDE,
    PokemonGen4.GRAVELER,
    PokemonGen4.ZUBAT,
    PokemonGen4.GOLBAT,
    PokemonGen4.ONIX,
    PokemonGen4.MAWILE,
    PokemonGen4.SABLEYE,
    PokemonGen4.STEELIX,
    PokemonGen4.RIOLU,
    PokemonGen4.TENTACOOL,
    PokemonGen4.WINGULL,
    PokemonGen4.TENTACRUEL,
    PokemonGen4.PELIPPER,
    PokemonGen4.GYARADOS,
    PokemonGen4.LUMINEON,
    PokemonGen4.QWILFISH,
    PokemonGen4.MAGIKARP,
    PokemonGen4.FINNEON,
},
"Lake Valor": {
    PokemonGen4.BIBAREL,
    PokemonGen4.STARAVIA,
    PokemonGen4.PSYDUCK,
    PokemonGen4.SOLROCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.LUNATONE,
    PokemonGen4.SEAKING,
    PokemonGen4.GYARADOS,
    PokemonGen4.GOLDEEN,
    PokemonGen4.MAGIKARP,
    PokemonGen4.WOBBUFFET,
    PokemonGen4.AZELF,
    PokemonGen4.NOCTOWL,
    PokemonGen4.CHINGLING,
    PokemonGen4.LICKITUNG,
},
"Valor Cavern": {},
"Acuity Lakefront": {
    PokemonGen4.SNEASEL,
    PokemonGen4.SNOVER,
    PokemonGen4.SNORUNT,
    PokemonGen4.ZUBAT,
    PokemonGen4.MACHOKE,
    PokemonGen4.NOCTOWL,
    PokemonGen4.MEDITITE,
    PokemonGen4.MEDICHAM,
    PokemonGen4.TEDDIURSA,
},
"Snowpoint City": {
    PokemonGen4.HAUNTER,
},
"Lake Acuity": {
    PokemonGen4.PSYDUCK,
    PokemonGen4.SNEASEL,
    PokemonGen4.BIBAREL,
    PokemonGen4.SOLROCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.LUNATONE,
    PokemonGen4.SEAKING,
    PokemonGen4.GYARADOS,
    PokemonGen4.GOLDEEN,
    PokemonGen4.MAGIKARP,
    PokemonGen4.UXIE,
    PokemonGen4.NOCTOWL,
    PokemonGen4.CHINGLING,
    PokemonGen4.URSARING,
    PokemonGen4.SMOOCHUM,
    PokemonGen4.WOBBUFFET,
},
"Team Galactic HQ": {},
"Sunyshore City": {
    PokemonGen4.TENTACRUEL,
    PokemonGen4.PELIPPER,
    PokemonGen4.GYARADOS,
    PokemonGen4.OCTILLERY,
    PokemonGen4.MAGIKARP,
    PokemonGen4.REMORAID,
    PokemonGen4.MANTYKE,
    PokemonGen4.STARYU,
},
"Pokémon League": {
    PokemonGen4.TENTACRUEL,
    PokemonGen4.PELIPPER,
    PokemonGen4.GYARADOS,
    PokemonGen4.OCTILLERY,
    PokemonGen4.LUVDISC,
    PokemonGen4.MAGIKARP,
    PokemonGen4.REMORAID,
},
"Victory Road": {
    PokemonGen4.GRAVELER,
    PokemonGen4.GOLBAT,
    PokemonGen4.STEELIX,
    PokemonGen4.ONIX,
    PokemonGen4.FLOATZEL,
    PokemonGen4.GYARADOS,
    PokemonGen4.MAGIKARP,
    PokemonGen4.LAPRAS,
    PokemonGen4.MACHOKE,
    PokemonGen4.MEDICHAM,
    PokemonGen4.KADABRA,
    PokemonGen4.REMORAID,
},
"Route 201",: {
    PokemonGen4.STARLY,
    PokemonGen4.BIDOOF,
    PokemonGen4.GROWLITHE,
    PokemonGen4.DODUO,
    PokemonGen4.NIDORAN_M,
},
"Route 202": {
    PokemonGen4.STARLY,
    PokemonGen4.BIDOOF,
    PokemonGen4.SHINX,
    PokemonGen4.KRICKETOT,
    PokemonGen4.GROWLITHE,
    PokemonGen4.ZIGZAGOON,
    PokemonGen4.SENTRET,
},
"Route 203": {
    PokemonGen4.STARLY,
    PokemonGen4.BIDOOF,
    PokemonGen4.SHINX,
    PokemonGen4.ZUBAT,
    PokemonGen4.ABRA,
    PokemonGen4.KRICKETOT,
    PokemonGen4.PINECO,
    PokemonGen4.SEEDOT,
    PokemonGen4.LOTAD,
    PokemonGen4.CUBONE,
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.SEAKING,
    PokemonGen4.GYARADOS,
    PokemonGen4.GOLDEEN,
    PokemonGen4.MAGIKARP,
    PokemonGen4.RALTS,
    PokemonGen4.KIRLIA,
},
"Route 204": {
    PokemonGen4.STARLY,
    PokemonGen4.BIDOOF,
    PokemonGen4.BUDEW,
    PokemonGen4.ZUBAT,
    PokemonGen4.KRICKETOT,
    PokemonGen4.SHINX,
    PokemonGen4.PINECO,
    PokemonGen4.SEEDOT,
    PokemonGen4.LOTAD,
    PokemonGen4.SUNKERN,
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.SEAKING,
    PokemonGen4.GYARADOS,
    PokemonGen4.GOLDEEN,
    PokemonGen4.MAGIKARP,
    PokemonGen4.RALTS,
    PokemonGen4.KIRLIA,
},
"Route 205": {
    PokemonGen4.BIDOOF,
    PokemonGen4.LOTAD,
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.GYARADOS,
    PokemonGen4.WHISCASH,
    PokemonGen4.MAGIKARP,
    PokemonGen4.BARBOACH,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.SHELLOS,
    PokemonGen4.PACHIRISU,
    PokemonGen4.BUIZEL,
    PokemonGen4.TENTACOOL,
    PokemonGen4.TENTACRUEL,
    PokemonGen4.LUMINEON,
    PokemonGen4.SHELLDER,
    PokemonGen4.FINNEON,
    PokemonGen4.LUMINEON,
    PokemonGen4.HOPPIP,
    PokemonGen4.ELEKID,
    PokemonGen4.WINGULL,
    PokemonGen4.PELIPPER,
    PokemonGen4.SKIPLOOM,
    PokemonGen4.SILCOON,
},
"Route 206": {
    PokemonGen4.GEODUDE,
    PokemonGen4.PONYTA,
    PokemonGen4.ZUBAT,
    PokemonGen4.KRICKETUNE,
    PokemonGen4.GLIGAR,
    PokemonGen4.BALTOY,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.BRONZOR,
    PokemonGen4.STUNKY,
    PokemonGen4.NOSEPASS,
    PokemonGen4.SILCOON,
},
"Route 207": {
    PokemonGen4.MACHOP,
    PokemonGen4.GEODUDE,
    PokemonGen4.ZUBAT,
    PokemonGen4.KRICKETOT,
    PokemonGen4.PHANPY,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.GLIGAR,
    PokemonGen4.LARVITAR,
    PokemonGen4.SILCOON,
},
"Route 208": {
    PokemonGen4.PSYDUCK,
    PokemonGen4.ZUBAT,
    PokemonGen4.BIDOOF,
    PokemonGen4.BIBAREL,
    PokemonGen4.ZANGOOSE,
    PokemonGen4.SEVIPER,
    PokemonGen4.DUNSPARCE,
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.GYARADOS,
    PokemonGen4.MAGIKARP,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.MACHOP,
    PokemonGen4.MEDITITE,
    PokemonGen4.WHISCASH,
    PokemonGen4.BARBOACH,
    PokemonGen4.TYROGUE,
    PokemonGen4.SILCOON,
},
"Route 209": {
    PokemonGen4.STARAVIA,
    PokemonGen4.BIBAREL,
    PokemonGen4.CHANSEY,
    PokemonGen4.ZUBAT,
    PokemonGen4.VULPIX,
    PokemonGen4.SNUBBULL,
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.SEAKING,
    PokemonGen4.GYARADOS,
    PokemonGen4.GOLDEEN,
    PokemonGen4.MAGIKARP,
    PokemonGen4.GASTLY,
    PokemonGen4.SPIRITOMB,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.MILTANK,
    PokemonGen4.TAUROS,
    PokemonGen4.STARLY,
    PokemonGen4.MIME_JR,
    PokemonGen4.SILCOON,
},
"Route 210": {
    PokemonGen4.MEDITITE,
    PokemonGen4.PSYDUCK,
    PokemonGen4.MACHOP,
    PokemonGen4.MACHOKE,
    PokemonGen4.HOOTHOOT,
    PokemonGen4.NOCTOWL,
    PokemonGen4.BIBAREL,
    PokemonGen4.ZANGOOSE,
    PokemonGen4.SEVIPER,
    PokemonGen4.GOLDUCK,
    PokemonGen4.GYARADOS,
    PokemonGen4.WHISCASH,
    PokemonGen4.MAGIKARP,
    PokemonGen4.BARBOACH,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.KECLEON,
    PokemonGen4.SILCOON,
},
"Route 211": {
    PokemonGen4.MEDITITE,
    PokemonGen4.ZUBAT,
    PokemonGen4.MACHOKE,
    PokemonGen4.GRAVELER,
    PokemonGen4.NOCTOWL,
    PokemonGen4.CHINGLING,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.BIDOOF,
    PokemonGen4.TYROGUE,
    PokemonGen4.PONYTA,
    PokemonGen4.TEDDIURSA,
    PokemonGen4.SWABLU,
    PokemonGen4.GEODUDE,
    PokemonGen4.SILCOON,
},
"Route 212": {
    PokemonGen4.STARAVIA,
    PokemonGen4.ROSELIA,
    PokemonGen4.GOLDUCK,
    PokemonGen4.SEAKING,
    PokemonGen4.GYARADOS,
    PokemonGen4.GOLDEEN,
    PokemonGen4.MAGIKARP,
    PokemonGen4.SMEARGLE,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.EKANS,
    PokemonGen4.LOTAD,
    PokemonGen4.LOMBRE,
    PokemonGen4.WOOPER,
    PokemonGen4.QUAGSIRE,
    PokemonGen4.GYARADOS,
    PokemonGen4.WHISCASH,
    PokemonGen4.MAGIKARP,
    PokemonGen4.GRIMER,
    PokemonGen4.KRICKETUNE,
    PokemonGen4.BUDEW,
    PokemonGen4.STARLY,
    PokemonGen4.WOOPER,
    PokemonGen4.BIBAREL,
    PokemonGen4.BARBOACH,
    PokemonGen4.SILCOON,
},
"Route 213": {
    PokemonGen4.BUIZEL,
    PokemonGen4.SHELLOS,
    PokemonGen4.WINGULL,
    PokemonGen4.TENTACOOL,
    PokemonGen4.WINGULL,
    PokemonGen4.TENTACRUEL,
    PokemonGen4.GYARADOS,
    PokemonGen4.OCTILLERY,
    PokemonGen4.MAGIKARP,
    PokemonGen4.REMORAID,
    PokemonGen4.SWELLOW,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.FLOATZEL,
    PokemonGen4.ABSOL,
    PokemonGen4.PELIPPER,
    PokemonGen4.SHARPEDO,
    PokemonGen4.SILCOON,
},
"Route 214": {
    PokemonGen4.GRAVELER,
    PokemonGen4.GEODUDE,
    PokemonGen4.VULPIX,
    PokemonGen4.SPOINK,
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.SEAKING,
    PokemonGen4.GYARADOS,
    PokemonGen4.GOLDEEN,
    PokemonGen4.MAGIKARP,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.PONYTA,
    PokemonGen4.KRICKETUNE,
    PokemonGen4.GIRAFARIG,
    PokemonGen4.GLIGAR,
    PokemonGen4.STUNKY,
    PokemonGen4.MIGHTYENA,
    PokemonGen4.SILCOON,
},
"Route 215": {
    PokemonGen4.ABRA,
    PokemonGen4.KADABRA,
    PokemonGen4.DROWZEE,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.GEODUDE,
    PokemonGen4.PONYTA,
    PokemonGen4.KRICKETUNE,
    PokemonGen4.GLIGAR,
    PokemonGen4.MIGHTYENA,
    PokemonGen4.SILCOON,
},
"Route 216": {
    PokemonGen4.SNEASEL,
    PokemonGen4.SNOVER,
    PokemonGen4.GRAVELER,
    PokemonGen4.ZUBAT,
    PokemonGen4.MEDITITE,
    PokemonGen4.URSARING,
    PokemonGen4.SNORUNT,
    PokemonGen4.SWINUB,
    PokemonGen4.MACHOKE,
    PokemonGen4.NOCTOWL,
    PokemonGen4.DELIBIRD,
},
"Route 217": {
    PokemonGen4.SNEASEL,
    PokemonGen4.SNOVER,
    PokemonGen4.SWINUB,
    PokemonGen4.SNORUNT,
    PokemonGen4.URSARING,
    PokemonGen4.ZUBAT,
    PokemonGen4.MACHOKE,
    PokemonGen4.NOCTOWL,
    PokemonGen4.MEDITITE,
    PokemonGen4.MEDICHAM,
},
"Route 218": {
    PokemonGen4.FLOATZEL,
    PokemonGen4.GASTRODON,
    PokemonGen4.VOLTORB,
    PokemonGen4.TENTACOOL,
    PokemonGen4.SHELLOS,
    PokemonGen4.TENTACRUEL,
    PokemonGen4.GYARADOS,
    PokemonGen4.LUMINEON,
    PokemonGen4.MAGIKARP,
    PokemonGen4.FINNEON,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.WINGULL,
    PokemonGen4.PELIPPER,
    PokemonGen4.DITTO,
    PokemonGen4.MR_MIME,
    PokemonGen4.SILCOON,
},
"Route 222": {
    PokemonGen4.FLOATZEL,
    PokemonGen4.PELIPPER,
    PokemonGen4.WINGULL,
    PokemonGen4.CHATOT,
    PokemonGen4.SKITTY,
    PokemonGen4.TENTACOOL,
    PokemonGen4.TENTACRUEL,
    PokemonGen4.GYARADOS,
    PokemonGen4.OCTILLERY,
    PokemonGen4.MAGIKARP,
    PokemonGen4.REMORAID,
    PokemonGen4.FLAAFFY,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.GASTRODON,
    PokemonGen4.SHARPEDO,
    PokemonGen4.MR_MIME,
    PokemonGen4.SILCOON,
},
"Route 223": {
    PokemonGen4.TENTACRUEL,
    PokemonGen4.PELIPPER,
    PokemonGen4.MANTYKE,
    PokemonGen4.GYARADOS,
    PokemonGen4.OCTILLERY,
    PokemonGen4.MAGIKARP,
    PokemonGen4.REMORAID,
    PokemonGen4.WAILORD,
},
}
)


PEARL = _BaseGen4Game(
    name="Pearl",
    encounters={
        "Twinleaf Town": {
            PokemonGen4.PSYDUCK, 
            PokemonGen4.GOLDUCK,
            PokemonGen4.SEAKING,
            PokemonGen4.GYARADOS,
            PokemonGen4.GOLDEEN,
            PokemonGen4.MAGIKARP,
        },
"Verity Lakefront": {},
"Sandgem Town": {},
"Jubilife City": {},
"Oreburgh Gate": {
    PokemonGen4.GEODUDE,
    PokemonGen4.ZUBAT.
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLBAT,
    PokemonGen4.GOLDUCK,
    PokemonGen4.GYARADOS,
    PokemonGen4.WHISCASH,
    PokemonGen4.MAGIKARP,
    PokemonGen4.BARBOACH,
},
"Oreburgh City": {
PokemonGen4.OMANYTE,
PokemonGen4.KABUTO,
PokemonGen4.AERODACTYL,
PokemonGen4.LILEEP,
PokemonGen4.ANORITH,
PokemonGen4.CRANIDOS,
PokemonGen4.SHIELDON,
PokemonGen4.ABRA,},
"Oreburgh Mine": {
    PokemonGen4.GEODUDE,
    PokemonGen4.ZUBAT.
    PokemonGen4.ONIX,
},
"Ravaged Path": {
    PokemonGen4.ZUBAT,
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLBAT,
    PokemonGen4.GOLDUCK,
    PokemonGen4.GYARADOS,
    PokemonGen4.WHISCASH,
    PokemonGen4.MAGIKARP,
    PokemonGen4.BARBOACH,
    PokemonGen4.GEODUDE,
},
"Floaroma Town": {},
"Valley Windworks": {
    PokemonGen4.PACHIRISU,
    PokemonGen4.BUIZEL,
    PokemonGen4.SHELLOS,
    PokemonGen4.ELEKID,
    PokemonGen4.ELECTRIKE,
    PokemonGen4.TENTACOOL,
    PokemonGen4.TENTACRUEL,
    PokemonGen4.GYARADOS,
    PokemonGen4.LUMINEON,
    PokemonGen4.SHELLDER,
    PokemonGen4.MAGIKARP,
    PokemonGen4.FINNEON,
    PokemonGen4.DRIFLOON,
    PokemonGen4.MAREEP,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.WINGULL,
    PokemonGen4.BIDOOF,
    PokemonGen4.PELIPPER,
    PokemonGen4.CASCOON,
},
"Eterna Forest": {
    PokemonGen4.WURMPLE,
    PokemonGen4.BUDEW,
    PokemonGen4.PINECO,
    PokemonGen4.METAPOD,
    PokemonGen4.KAKUNA,
    PokemonGen4.SEEDOT,
    PokemonGen4.SLAKOTH,
    PokemonGen4.NINCADA,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.DUSTOX,
    PokemonGen4.MISDREAVUS,
},
"Old Chateau": {
    PokemonGen4.GASTLY,
    PokemonGen4.ROTOM,
    PokemonGen4.GENGAR,
    PokemonGen4.HAUNTER,
},
"Eterna City": {
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.GYARADOS,
    PokemonGen4.WHISCASH,
    PokemonGen4.MAGIKARP,
    PokemonGen4.BARBOACH,
    PokemonGen4.CHATOT,
},
"Wayward Cave": {
    PokemonGen4.ZUBAT,
    PokemonGen4.BRONZOR,
    PokemonGen4.GEODUDE,
    PokemonGen4.SANDSHREW,
},
"Mt. Coronet": {
    PokemonGen4.GRAVELER, # all
    PokemonGen4.BRONZOR,
    PokemonGen4.GOLBAT,
    PokemonGen4.CLEFAIRY,
    PokemonGen4.MACHOKE,
    PokemonGen4.MEDICHAM,
    PokemonGen4.CHINGLING,
    PokemonGen4.BRONZONG,
    PokemonGen4.SOLROCK,
    PokemonGen4.LUNATONE,
    PokemonGen4.GYARADOS,
    PokemonGen4.DRATINI,
    PokemonGen4.DRAGONAIR,
    PokemonGen4.WHISCASH,
    PokemonGen4.MAGIKARP,
    PokemonGen4.BARBOACH,
    PokemonGen4.CHIMECHO,
    PokemonGen4.MEDITITE,
    PokemonGen4.FEEBAS,
    PokemonGen4.MACHOP,
    PokemonGen4.GEODUDE,
    PokemonGen4.CLEFFA,
    PokemonGen4.ZUBAT,
    PokemonGen4.ABOMASNOW,
    PokemonGen4.NOCTOWL,
    PokemonGen4.SNOVER,
    PokemonGen4.LOUDRED,
},
"Hearthome City": {},
"Hallowed Tower": {},
"Lost Tower": {
    PokemonGen4.ZUBAT,
    PokemonGen4.GASTLY,
    PokemonGen4.GOLBAT,
    PokemonGen4.MISDREAVUS,
},
"Solaceon Town": {},
"Solaceon Ruins": {
    PokemonGen4.UNOWN,
},
"Veilstone City": {},
"Café Cabin": {},
"Galactic Warehouse": {},
"Ruin Maniac Cave": {
    PokemonGen4.GEODUDE,
    PokemonGen4.HIPPOPOTAS,
},
"Valor Lakefront": {
    PokemonGen4.GIRAFARIG,
    PokemonGen4.KRICKETUNE,
    PokemonGen4.STARVIA,
    PokemonGen4.BIBAREL,
    PokemonGen4.GRAVELER,
    PokemonGen4.GEODUDE,
    PokemonGen4.NIDORINO,
},
"Pastoria City": {
    PokemonGen4.TENTACOOL,
    PokemonGen4.TENTACRUEL,
    PokemonGen4.GYARADOS,
    PokemonGen4.OCTILLERY,
    PokemonGen4.MAGIKARP,
    PokemonGen4.REMORAID,
    PokemonGen4.WINGULL,
    PokemonGen4.PELIPPER,
},
"Great Marsh": {
    PokemonGen4.PSYDUCK,
    PokemonGen4.AZURILL,
    PokemonGen4.BIDOOF,
    PokemonGen4.HOOTHOOT,
    PokemonGen4.NOCTOWL,
    PokemonGen4.MARILL,
    PokemonGen4.WOOOPER,
    PokemonGen4.QUAGSIRE,
    PokemonGen4.STARLY,
    PokemonGen4.BIBAREL,
    PokemonGen4.BUDEW,
    PokemonGen4.ARBOK,
    PokemonGen4.CARVANHA,
    PokemonGen4.WHISCASH,
    PokemonGen4.GYARADOS,
    PokemonGen4.MAGIKARP,
    PokemonGen4.BARBOACH,
    PokemonGen4.PARAS,
    PokemonGen4.GOLDUCK,
    PokemonGen4.EXEGGCUTE,
    PokemonGen4.KANGASKHAN,
    PokemonGen4.SHROOMISH, 
    PokemonGen4.ROSELIA,
    PokemonGen4.GULPIN,
    PokemonGen4.STARAVIA,
    PokemonGen4.SKORUPI,
    PokemonGen4.DRAPION,
    PokemonGen4.CROAGUNK,
    PokemonGen4.TOXICROAK,
    PokemonGen4.CARNIVINE,
},
"Pokémon Mansion": {},
"Trophy Garden": {
    PokemonGen4.PICHU,
    PokemonGen4.ROSELIA,
    PokemonGen4.STARAVIA,
    PokemonGen4.KRICKETUNE,
    PokemonGen4.PIKACHU,
    PokemonGen4.CLEFAIRY,
    PokemonGen4.JIGGLYPUFF,
    PokemonGen4.MEOWTH,
    PokemonGen4.CHANSEY,
    PokemonGen4.EEVEE,
    PokemonGen4.CLEFFA,
    PokemonGen4.IGGLYBUFF,
    PokemonGen4.MARILL,
    PokemonGen4.AZURILL,
    PokemonGen4.PLUSLE,
    PokemonGen4.MINUN,
    PokemonGen4.CASTFORM,
    PokemonGen4.BONSLY,
    PokemonGen4.MIME_JR,
    PokemonGen4.HAPPINY,
    PokemonGen4.PORYGON,
},
"Celestic Town": {
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.GYARADOS,
    PokemonGen4.CORPHISH,
    PokemonGen4.CRAWDAUNT,
    PokemonGen4.MAGIKARP,
    PokemonGen4.WHISCASH,
    PokemonGen4.BARBOACH,
},
"Celestic Ruins": {},
"Canalave City": {
    PokemonGen4.TENTACOOL,
    PokemonGen4.TENTACRUEL,
    PokemonGen4.GYARADOS,
    PokemonGen4.LUMINEON,
    PokemonGen4.STARYU,
    PokemonGen4.MAGIKARP,
    PokemonGen4.FINNEON,
    PokemonGen4.WINGULL,
    PokemonGen4.PELIPPER,
},
"Iron Island": {
    PokemonGen4.GEODUDE,
    PokemonGen4.GRAVELER,
    PokemonGen4.ZUBAT,
    PokemonGen4.GOLBAT,
    PokemonGen4.ONIX,
    PokemonGen4.MAWILE,
    PokemonGen4.SABLEYE,
    PokemonGen4.STEELIX,
    PokemonGen4.RIOLU,
    PokemonGen4.TENTACOOL,
    PokemonGen4.WINGULL,
    PokemonGen4.TENTACRUEL,
    PokemonGen4.PELIPPER,
    PokemonGen4.GYARADOS,
    PokemonGen4.LUMINEON,
    PokemonGen4.QWILFISH,
    PokemonGen4.MAGIKARP,
    PokemonGen4.FINNEON,
},
"Lake Valor": {
    PokemonGen4.BIBAREL,
    PokemonGen4.STARAVIA,
    PokemonGen4.PSYDUCK,
    PokemonGen4.SOLROCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.LUNATONE,
    PokemonGen4.SEAKING,
    PokemonGen4.GYARADOS,
    PokemonGen4.GOLDEEN,
    PokemonGen4.MAGIKARP,
    PokemonGen4.WOBBUFFET,
    PokemonGen4.AZELF,
    PokemonGen4.NOCTOWL,
    PokemonGen4.CHINGLING,
    PokemonGen4.LICKITUNG,
},
"Valor Cavern": {},
"Acuity Lakefront": {
    PokemonGen4.SNEASEL,
    PokemonGen4.SNOVER,
    PokemonGen4.SNORUNT,
    PokemonGen4.ZUBAT,
    PokemonGen4.MACHOKE,
    PokemonGen4.NOCTOWL,
    PokemonGen4.MEDITITE,
    PokemonGen4.MEDICHAM,
    PokemonGen4.TEDDIURSA,
},
"Snowpoint City": {
    PokemonGen4.HAUNTER,
},
"Lake Acuity": {
    PokemonGen4.PSYDUCK,
    PokemonGen4.SNEASEL,
    PokemonGen4.BIBAREL,
    PokemonGen4.SOLROCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.LUNATONE,
    PokemonGen4.SEAKING,
    PokemonGen4.GYARADOS,
    PokemonGen4.GOLDEEN,
    PokemonGen4.MAGIKARP,
    PokemonGen4.UXIE,
    PokemonGen4.NOCTOWL,
    PokemonGen4.CHINGLING,
    PokemonGen4.URSARING,
    PokemonGen4.SMOOCHUM,
    PokemonGen4.WOBBUFFET,
},
"Team Galactic HQ": {},
"Sunyshore City": {
    PokemonGen4.TENTACRUEL,
    PokemonGen4.PELIPPER,
    PokemonGen4.GYARADOS,
    PokemonGen4.OCTILLERY,
    PokemonGen4.MAGIKARP,
    PokemonGen4.REMORAID,
    PokemonGen4.MANTYKE,
    PokemonGen4.STARYU,
},
"Pokémon League": {
    PokemonGen4.TENTACRUEL,
    PokemonGen4.PELIPPER,
    PokemonGen4.GYARADOS,
    PokemonGen4.OCTILLERY,
    PokemonGen4.LUVDISC,
    PokemonGen4.MAGIKARP,
    PokemonGen4.REMORAID,
},
"Victory Road": {
    PokemonGen4.GRAVELER,
    PokemonGen4.GOLBAT,
    PokemonGen4.STEELIX,
    PokemonGen4.ONIX,
    PokemonGen4.FLOATZEL,
    PokemonGen4.GYARADOS,
    PokemonGen4.MAGIKARP,
    PokemonGen4.LAPRAS,
    PokemonGen4.MACHOKE,
    PokemonGen4.MEDICHAM,
    PokemonGen4.KADABRA,
    PokemonGen4.REMORAID,
},
"Route 201",: {
    PokemonGen4.STARLY,
    PokemonGen4.BIDOOF,
    PokemonGen4.GROWLITHE,
    PokemonGen4.DODUO,
    PokemonGen4.NIDORAN_F,
},
"Route 202": {
    PokemonGen4.STARLY,
    PokemonGen4.BIDOOF,
    PokemonGen4.SHINX,
    PokemonGen4.KRICKETOT,
    PokemonGen4.GROWLITHE,
    PokemonGen4.ZIGZAGOON,
    PokemonGen4.SENTRET,
},
"Route 203": {
    PokemonGen4.STARLY,
    PokemonGen4.BIDOOF,
    PokemonGen4.SHINX,
    PokemonGen4.ZUBAT,
    PokemonGen4.ABRA,
    PokemonGen4.KRICKETOT,
    PokemonGen4.PINECO,
    PokemonGen4.SEEDOT,
    PokemonGen4.LOTAD,
    PokemonGen4.CUBONE,
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.SEAKING,
    PokemonGen4.GYARADOS,
    PokemonGen4.GOLDEEN,
    PokemonGen4.MAGIKARP,
    PokemonGen4.RALTS,
    PokemonGen4.KIRLIA,
},
"Route 204": {
    PokemonGen4.STARLY,
    PokemonGen4.BIDOOF,
    PokemonGen4.BUDEW,
    PokemonGen4.ZUBAT,
    PokemonGen4.KRICKETOT,
    PokemonGen4.SHINX,
    PokemonGen4.PINECO,
    PokemonGen4.SEEDOT,
    PokemonGen4.LOTAD,
    PokemonGen4.SUNKERN,
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.SEAKING,
    PokemonGen4.GYARADOS,
    PokemonGen4.GOLDEEN,
    PokemonGen4.MAGIKARP,
    PokemonGen4.RALTS,
    PokemonGen4.KIRLIA,
},
"Route 205": {
    PokemonGen4.BIDOOF,
    PokemonGen4.LOTAD,
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.GYARADOS,
    PokemonGen4.WHISCASH,
    PokemonGen4.MAGIKARP,
    PokemonGen4.BARBOACH,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.SHELLOS,
    PokemonGen4.PACHIRISU,
    PokemonGen4.BUIZEL,
    PokemonGen4.TENTACOOL,
    PokemonGen4.TENTACRUEL,
    PokemonGen4.LUMINEON,
    PokemonGen4.SHELLDER,
    PokemonGen4.FINNEON,
    PokemonGen4.LUMINEON,
    PokemonGen4.HOPPIP,
    PokemonGen4.ELEKID,
    PokemonGen4.WINGULL,
    PokemonGen4.PELIPPER,
    PokemonGen4.SLOWPOKE,
    PokemonGen4.CASCOON,
},
"Route 206": {
    PokemonGen4.GEODUDE,
    PokemonGen4.PONYTA,
    PokemonGen4.ZUBAT,
    PokemonGen4.KRICKETUNE,
    PokemonGen4.GLIGAR,
    PokemonGen4.BALTOY,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.BRONZOR,
    PokemonGen4.STUNKY,
    PokemonGen4.NOSEPASS,
    PokemonGen4.CASCOON,
},
"Route 207": {
    PokemonGen4.MACHOP,
    PokemonGen4.GEODUDE,
    PokemonGen4.ZUBAT,
    PokemonGen4.KRICKETOT,
    PokemonGen4.PHANPY,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.GLIGAR,
    PokemonGen4.STANTLER,
    PokemonGen4.CASCOON,
},
"Route 208": {
    PokemonGen4.PSYDUCK,
    PokemonGen4.ZUBAT,
    PokemonGen4.BIDOOF,
    PokemonGen4.BIBAREL,
    PokemonGen4.ZANGOOSE,
    PokemonGen4.SEVIPER,
    PokemonGen4.DUNSPARCE,
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.GYARADOS,
    PokemonGen4.MAGIKARP,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.MACHOP,
    PokemonGen4.MEDITITE,
    PokemonGen4.WHISCASH,
    PokemonGen4.BARBOACH,
    PokemonGen4.TYROGUE,
    PokemonGen4.CASCOON,
},
"Route 209": {
    PokemonGen4.STARAVIA,
    PokemonGen4.BIBAREL,
    PokemonGen4.CHANSEY,
    PokemonGen4.ZUBAT,
    PokemonGen4.VULPIX,
    PokemonGen4.SNUBBULL,
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.SEAKING,
    PokemonGen4.GYARADOS,
    PokemonGen4.GOLDEEN,
    PokemonGen4.MAGIKARP,
    PokemonGen4.SPIRITOMB,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.MILTANK,
    PokemonGen4.TAUROS,
    PokemonGen4.GASTLY,
    PokemonGen4.BONSLY,
    PokemonGen4.CASCOON,
},
"Route 210": {
    PokemonGen4.MEDITITE,
    PokemonGen4.PSYDUCK,
    PokemonGen4.MACHOP,
    PokemonGen4.MACHOKE,
    PokemonGen4.HOOTHOOT,
    PokemonGen4.NOCTOWL,
    PokemonGen4.BIBAREL,
    PokemonGen4.ZANGOOSE,
    PokemonGen4.SEVIPER,
    PokemonGen4.GOLDUCK,
    PokemonGen4.GYARADOS,
    PokemonGen4.WHISCASH,
    PokemonGen4.MAGIKARP,
    PokemonGen4.BARBOACH,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.BAGON,
    PokemonGen4.CASCOON,
},
"Route 211": {
    PokemonGen4.MEDITITE,
    PokemonGen4.ZUBAT,
    PokemonGen4.MACHOKE,
    PokemonGen4.GRAVELER,
    PokemonGen4.NOCTOWL,
    PokemonGen4.CHINGLING,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.BIDOOF,
    PokemonGen4.TYROGUE,
    PokemonGen4.PONYTA,
    PokemonGen4.TEDDIURSA,
    PokemonGen4.SWABLU,
    PokemonGen4.GEODUDE,
    PokemonGen4.CASCOON,
},
"Route 212": {
    PokemonGen4.STARAVIA,
    PokemonGen4.ROSELIA,
    PokemonGen4.GOLDUCK,
    PokemonGen4.SEAKING,
    PokemonGen4.GYARADOS,
    PokemonGen4.GOLDEEN,
    PokemonGen4.MAGIKARP,
    PokemonGen4.SMEARGLE,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.EKANS,
    PokemonGen4.LOTAD,
    PokemonGen4.LOMBRE,
    PokemonGen4.WOOPER,
    PokemonGen4.QUAGSIRE,
    PokemonGen4.GYARADOS,
    PokemonGen4.WHISCASH,
    PokemonGen4.MAGIKARP,
    PokemonGen4.GRIMER,
    PokemonGen4.KRICKETUNE,
    PokemonGen4.BUDEW,
    PokemonGen4.STARLY,
    PokemonGen4.WOOPER,
    PokemonGen4.BIBAREL,
    PokemonGen4.BARBOACH,
    PokemonGen4.CASCOON,
},
"Route 213": {
    PokemonGen4.BUIZEL,
    PokemonGen4.SHELLOS,
    PokemonGen4.WINGULL,
    PokemonGen4.TENTACOOL,
    PokemonGen4.WINGULL,
    PokemonGen4.TENTACRUEL,
    PokemonGen4.GYARADOS,
    PokemonGen4.OCTILLERY,
    PokemonGen4.MAGIKARP,
    PokemonGen4.REMORAID,
    PokemonGen4.SWELLOW,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.FLOATZEL,
    PokemonGen4.ABSOL,
    PokemonGen4.PELIPPER,
    PokemonGen4.SHARPEDO,
    PokemonGen4.CASCOON,
},
"Route 214": {
    PokemonGen4.GRAVELER,
    PokemonGen4.GEODUDE,
    PokemonGen4.VULPIX,
    PokemonGen4.SPOINK,
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.SEAKING,
    PokemonGen4.GYARADOS,
    PokemonGen4.GOLDEEN,
    PokemonGen4.MAGIKARP,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.PONYTA,
    PokemonGen4.KRICKETUNE,
    PokemonGen4.GIRAFARIG,
    PokemonGen4.GLIGAR,
    PokemonGen4.SUDOWOODO,
    PokemonGen4.HOUNDOOM,
    PokemonGen4.CASCOON,
},
"Route 215": {
    PokemonGen4.ABRA,
    PokemonGen4.KADABRA,
    PokemonGen4.DROWZEE,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.GEODUDE,
    PokemonGen4.PONYTA,
    PokemonGen4.KRICKETUNE,
    PokemonGen4.GLIGAR,
    PokemonGen4.HOUNDOOM,
    PokemonGen4.CASCOON,
},
"Route 216": {
    PokemonGen4.SNEASEL,
    PokemonGen4.SNOVER,
    PokemonGen4.GRAVELER,
    PokemonGen4.ZUBAT,
    PokemonGen4.MEDITITE,
    PokemonGen4.URSARING,
    PokemonGen4.SNORUNT,
    PokemonGen4.MACHOKE,
    PokemonGen4.NOCTOWL,
    PokemonGen4.DELIBIRD,
},
"Route 217": {
    PokemonGen4.SNEASEL,
    PokemonGen4.SNOVER,
    PokemonGen4.SWINUB,
    PokemonGen4.SNORUNT,
    PokemonGen4.URSARING,
    PokemonGen4.ZUBAT,
    PokemonGen4.MACHOKE,
    PokemonGen4.NOCTOWL,
    PokemonGen4.MEDITITE,
    PokemonGen4.MEDICHAM,
},
"Route 218": {
    PokemonGen4.FLOATZEL,
    PokemonGen4.GASTRODON,
    PokemonGen4.VOLTORB,
    PokemonGen4.TENTACOOL,
    PokemonGen4.SHELLOS,
    PokemonGen4.TENTACRUEL,
    PokemonGen4.GYARADOS,
    PokemonGen4.LUMINEON,
    PokemonGen4.MAGIKARP,
    PokemonGen4.FINNEON,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.WINGULL,
    PokemonGen4.PELIPPER,
    PokemonGen4.DITTO,
    PokemonGen4.GLAMEOW,
    PokemonGen4.CASCOON,
},
"Route 222": {
    PokemonGen4.FLOATZEL,
    PokemonGen4.PELIPPER,
    PokemonGen4.WINGULL,
    PokemonGen4.CHATOT,
    PokemonGen4.SKITTY,
    PokemonGen4.TENTACOOL,
    PokemonGen4.TENTACRUEL,
    PokemonGen4.GYARADOS,
    PokemonGen4.OCTILLERY,
    PokemonGen4.MAGIKARP,
    PokemonGen4.REMORAID,
    PokemonGen4.FLAAFFY,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.GASTRODON,
    PokemonGen4.SHARPEDO,
    PokemonGen4.GLAMEOW,
    PokemonGen4.PURUGLY,
    PokemonGen4.CASCOON,
},
"Route 223": {
    PokemonGen4.TENTACRUEL,
    PokemonGen4.PELIPPER,
    PokemonGen4.MANTYKE,
    PokemonGen4.GYARADOS,
    PokemonGen4.OCTILLERY,
    PokemonGen4.MAGIKARP,
    PokemonGen4.REMORAID,
    PokemonGen4.WAILORD,
},
}
)


PLATINUM = _BaseRSGame(
    name="Platinum",
    gyms=[
        GymTrainer(
            leader="Roark",
            type=Types.ROCK,
            pokemons=[
                TrainerPokemon(PokemonGen4.GEODUDE, 12),
                TrainerPokemon(PokemonGen4.ONIX, 12),
                TrainerPokemon(PokemonGen4.CRANIDOS, 14),
            ],
            location="Oreburgh City",
            badge="Coal Badge"
        ),
        GymTrainer(
            leader="Gardenia",
            type=Types.GRASS,
            pokemons=[
                TrainerPokemon(PokemonGen4.CHERRIM, 20),
                TrainerPokemon(PokemonGen4.TURTWIG, 20),
                TrainerPokemon(PokemonGen4.ROSERADE, 22),
            ],
            location="Eterna City",
            badge="Forest Badge"
        ),
        GymTrainer(
            leader="Maylene",
            type=Types.FIGHTING,
            pokemons=[
                TrainerPokemon(PokemonGen4.MEDITITE, 28),
                TrainerPokemon(PokemonGen4.MACHOKE, 29),
                TrainerPokemon(PokemonGen4.LUCARIO, 32),
            ],
            location="Veilstone City",
            badge="Cobal Badge"
        ),
        GymTrainer(
            leader="Crasher Wake",
            type=Types.WATER,
            pokemons=[
                TrainerPokemon(PokemonGen4.GYARADOS, 33),
                TrainerPokemon(PokemonGen4.QUAGSIRE, 34),
                TrainerPokemon(PokemonGen4.FLOATZEL, 37),
            ],
            location="Pastoria City",
            badge="Fen Badge"
        ),
        GymTrainer(
            leader="Fantina",
            type=Types.GHOST,
            pokemons=[
                TrainerPokemon(PokemonGen4.DUSKULL, 24),
                TrainerPokemon(PokemonGen4.HAUNTER, 24),
                TrainerPokemon(PokemonGen4.MISMAGIUS, 26),
            ],
            location="Hearthome City",
            badge="Relic Badge"
        ),
        GymTrainer(
            leader="Byron",
            type=Types.STEEL,
            pokemons=[
                TrainerPokemon(PokemonGen4.MAGNETON, 37),
                TrainerPokemon(PokemonGen4.STEELIX, 38),
                TrainerPokemon(PokemonGen4.BASTIODON, 41),
            ],
            location="Canalave City",
            badge="Mine Badge"
        ),
        GymTrainer(
            leader="Candice",
            type=Types.ICE,
            pokemons=[
                TrainerPokemon(PokemonGen4.PILOSWINE, 40),
                TrainerPokemon(PokemonGen4.SNEASEL, 40),
                TrainerPokemon(PokemonGen4.FROSLAS, 44),
                TrainerPokemon(PokemonGen4.ABOMASNOW, 42),
            ],
            location="Snowpoint City",
            badge="Icicle Badge"
        ),
        GymTrainer(
            leader="Volkner",
            type=Types.ELECTRIC,
            pokemons=[
                TrainerPokemon(PokemonGen4.RAICHU, 46),
                TrainerPokemon(PokemonGen4.JOLTEON, 46),
                TrainerPokemon(PokemonGen4.ELECTIVIRE, 50),
                TrainerPokemon(PokemonGen4.LUXRAY, 48),
            ],
            location="Sunyshore City",
            badge="Beacon Badge"
        ),
    ],
    elite4=[
        EliteTrainer(
            leader="Aaron", type=Types.BUG, pokemons=[
                TrainerPokemon(PokemonGen4.YANMEGA, 49),
                TrainerPokemon(PokemonGen4.SCIZOR, 49),
                TrainerPokemon(PokemonGen4.HERACROSS, 51),
                TrainerPokemon(PokemonGen4.VESPIQUEN, 50),
                TrainerPokemon(PokemonGen4.DRAPION, 53),
            ]
        ),
        EliteTrainer(
            leader="Bertha", type=Types.GROUND, pokemons=[
                TrainerPokemon(PokemonGen4.GLISCOR, 53),
                TrainerPokemon(PokemonGen4.WHISCASH, 50),
                TrainerPokemon(PokemonGen4.GOLEM, 52),
                TrainerPokemon(PokemonGen4.RHYPERIOR, 52),
                TrainerPokemon(PokemonGen4.HIPPOWDON, 55),
            ]
        ),
        EliteTrainer(
            leader="Flint", type=Types.FIRE, pokemons=[
                TrainerPokemon(PokemonGen4.HOUNDOOM, 52),
                TrainerPokemon(PokemonGen4.FLAREON, 55),
                TrainerPokemon(PokemonGen4.RAPIDASH, 53),
                TrainerPokemon(PokemonGen4.INFERNAPE, 55),
                TrainerPokemon(PokemonGen4.MAGMORTAR, 57),
            ]
        ),
        EliteTrainer(
            leader="Lucian", type=Types.PSYCHIC, pokemons=[
                TrainerPokemon(PokemonGen4.MR_MIME, 53),
                TrainerPokemon(PokemonGen4.ESPEON, 55),
                TrainerPokemon(PokemonGen4.BRONZONG, 54),
                TrainerPokemon(PokemonGen4.ALAKAZAM, 56),
                TrainerPokemon(PokemonGen4.GALLADE, 59),
            ]
        ),
    ],
    routes=[
        "TWinleaf Town",
        "Lake Verity",
        "Verity Lakefront",
        "Sandgem Town",
        "Jubilife City",
        "Oreburgh Gate",
        "Oreburgh City",
        "Oreburgh Mine",
        "Ravaged Path",
        "Floaroma Town",
        "Floaroma Meadow",
        "Valley Windworks",
        "Eterna Forest",
        "Eterna City",
        "Team Galactic Eterna Building",
        "Old Chateau",
        "Wayward Cave",
        "Mt. Coronet",
        "Amity Square",
        "Hearthome City",
        "Solaceon Town",
        "Solaceon Ruins",
        "Café Cabin",
        "Lost Tower",
        "Veilstone City",
        "Maniac Tunnel",
        "Valor Lakefront",
        "Pastoria City",
        "Pokemon Mansion",
        "Celestic Town",
        "Fuego Ironworks",
        "Canalave City",
        "Iron Island",
        "Acuity Lakefront",
        "Snowpoint City",
        "Lake Acuity",
        "Lake Valor",
        "Galactic Warehouse",
        "Team Galactic HQ",
        "Spear Pillar",
        "Distortion World",
        "Sendoff Spring",
        "Sunnyshore City",
        "Pokemon League",
        "Victory Road",
        "Route 201",
        "Route 202",
        "Route 203",
        "Route 204",
        "Route 205",
        "Route 206",
        "Route 207",
        "Route 208",
        "Route 209",
        "Route 210",
        "Route 211",
        "Route 212",
        "Route 213",
        "Route 214",
        "Route 215",
        "Route 216",
        "Route 217",
        "Route 218",
        "Route 219",
        "Route 220",
        "Route 221",
        "Route 222",
        "Route 223",
    ],
    encounters={
        "Twinleaf Town": {
            PokemonGen4.PSYDUCK, 
            PokemonGen4.GOLDUCK,
            PokemonGen4.SEAKING,
            PokemonGen4.GYARADOS,
            PokemonGen4.GOLDEEN,
            PokemonGen4.MAGIKARP,
        },
"Verity Lakefront": {},
"Sandgem Town": {},
"Jubilife City": {},
"Oreburgh Gate": {
    PokemonGen4.GEODUDE,
    PokemonGen4.ZUBAT.
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLBAT,
    PokemonGen4.GOLDUCK,
    PokemonGen4.GYARADOS,
    PokemonGen4.WHISCASH,
    PokemonGen4.MAGIKARP,
    PokemonGen4.BARBOACH,
},
"Oreburgh City": {
PokemonGen4.OMANYTE,
PokemonGen4.KABUTO,
PokemonGen4.AERODACTYL,
PokemonGen4.LILEEP,
PokemonGen4.ANORITH,
PokemonGen4.CRANIDOS,
PokemonGen4.SHIELDON,
PokemonGen4.ABRA,
},
"Oreburgh Mine": {
    PokemonGen4.GEODUDE,
    PokemonGen4.ZUBAT.
    PokemonGen4.ONIX,
},
"Ravaged Path": {
    PokemonGen4.ZUBAT,
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLBAT,
    PokemonGen4.GOLDUCK,
    PokemonGen4.GYARADOS,
    PokemonGen4.WHISCASH,
    PokemonGen4.MAGIKARP,
    PokemonGen4.BARBOACH,
},
"Floaroma Town": {},
"Valley Windworks": {
    PokemonGen4.SHINX,
    PokemonGen4.GASTRODON,
    PokemonGen4.PACHIRISU,
    PokemonGen4.BUIZEL,
    PokemonGen4.SHELLOS,
    PokemonGen4.ELEKID,
    PokemonGen4.ELECTRIKE,
    PokemonGen4.TENTACOOL,
    PokemonGen4.TENTACRUEL,
    PokemonGen4.GYARADOS,
    PokemonGen4.LUMINEON,
    PokemonGen4.SHELLDER,
    PokemonGen4.MAGIKARP,
    PokemonGen4.FINNEON,
    PokemonGen4.DRIFLOON,
    PokemonGen4.MAREEP,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
},
"Eterna Forest": {
    PokemonGen4.WURMPLE,
    PokemonGen4.BUDEW,
    PokemonGen4.PINECO,
    PokemonGen4.METAPOD,
    PokemonGen4.KAKUNA,
    PokemonGen4.SEEDOT,
    PokemonGen4.SLAKOTH,
    PokemonGen4.NINCADA,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.GASTLY,
    PokemonGen4.SILCOON,
    PokemonGen4.BEAUTIFLY,
    PokemonGen4.CASCOON,
    PokemonGen4.DUSTOX,
    PokemonGen4.HOOTHOOT,
    PokemonGen4.BIDOOF,
    PokemonGen4.KRICKETOT,
    PokemonGen4.BUNEARY,
    PokemonGen4.CATERPIE,
    PokemonGen4.WEEDLE,
},
"Old Chateau": {
    PokemonGen4.GASTLY,
    PokemonGen4.ROTOM,
    PokemonGen4.GENGAR,
},
"Eterna City": {
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.GYARADOS,
    PokemonGen4.WHISCASH,
    PokemonGen4.MAGIKARP,
    PokemonGen4.BARBOACH,
    PokemonGen4.CHATOT,
    PokemonGen4.TOGEPI,
},
"Wayward Cave": {
    PokemonGen4.ZUBAT,
    PokemonGen4.BRONZOR,
    PokemonGen4.GEODUDE,
    PokemonGen4.SANDSHREW,
    PokemonGen4.ONIX,
},
"Mt. Coronet": {
    PokemonGen4.GRAVELER, # all
    PokemonGen4.BRONZOR,
    PokemonGen4.GOLBAT,
    PokemonGen4.CLEFAIRY,
    PokemonGen4.MACHOKE,
    PokemonGen4.MEDICHAM,
    PokemonGen4.CHINGLING,
    PokemonGen4.BRONZONG,
    PokemonGen4.SOLROCK,
    PokemonGen4.LUNATONE,
    PokemonGen4.GYARADOS,
    PokemonGen4.DRATINI,
    PokemonGen4.DRAGONAIR,
    PokemonGen4.WHISCASH,
    PokemonGen4.MAGIKARP,
    PokemonGen4.BARBOACH,
    PokemonGen4.CHIMECHO,
    PokemonGen4.MEDITITE,
    PokemonGen4.FEEBAS,
    PokemonGen4.MACHOP,
    PokemonGen4.GEODUDE,
    PokemonGen4.CLEFFA,
    PokemonGen4.ZUBAT,
    PokemonGen4.ABOMASNOW,
    PokemonGen4.NOCTOWL,
    PokemonGen4.SNOVER,
    PokemonGen4.LOUDRED,
    PokemonGen4.NOSEPASS,
    PokemonGen4.ABSOL,
    PokemonGen4.REGICE,
},
"Hearthome City": {},
"Hallowed Tower": {},
"Lost Tower": {
    PokemonGen4.ZUBAT,
    PokemonGen4.GASTLY,
    PokemonGen4.DUSKULL,
},
"Solaceon Town": {},
"Solaceon Ruins": {
    PokemonGen4.UNOWN,
},
"Veilstone City": {PokemonGen4.PORYGON},
"Café Cabin": {},
"Galactic Warehouse": {},
"Ruin Maniac Cave": {
    PokemonGen4.GEODUDE,
    PokemonGen4.HIPPOPOTAS,
},
"Valor Lakefront": {
    PokemonGen4.GIRAFARIG,
    PokemonGen4.KRICKETUNE,
    PokemonGen4.STARVIA,
    PokemonGen4.BIBAREL,
    PokemonGen4.HOUNDOUR,
    PokemonGen4.NIDORINA,
    PokemonGen4.NIDORINO,
},
"Pastoria City": {
    PokemonGen4.TENTACOOL,
    PokemonGen4.TENTACRUEL,
    PokemonGen4.GYARADOS,
    PokemonGen4.OCTILLERY,
    PokemonGen4.MAGIKARP,
    PokemonGen4.REMORAID,
    PokemonGen4.SHELLOS,
    PokemonGen4.GASTRODON,
},
"Great Marsh": {
    PokemonGen4.WOOPER,
    PokemonGen4.TANGELA,
    PokemonGen4.NOCTOWL,
    PokemonGen4.QUAGSIRE,
    PokemonGen4.TROPIUS,
    PokemonGen4.BIBAREL,
    PokemonGen4.ARBOK,
    PokemonGen4.CARVANHA,
    PokemonGen4.WHISCASH,
    PokemonGen4.GYARADOS,
    PokemonGen4.MAGIKARP,
    PokemonGen4.BARBOACH,
    PokemonGen4.YANMA,
    PokemonGen4.PARAS,
    PokemonGen4.EXEGGCUTE,
    PokemonGen4.KANGASKHAN,
    PokemonGen4.SHROOMISH, 
    PokemonGen4.ROSELIA,
    PokemonGen4.GULPIN,
    PokemonGen4.STARAVIA,
    PokemonGen4.SKORUPI,
    PokemonGen4.DRAPION,
    PokemonGen4.CROAGUNK,
    PokemonGen4.TOXICROAK,
    PokemonGen4.CARNIVINE,
    PokemonGen4.KECLEON,
},
"Pokémon Mansion": {},
"Trophy Garden": {
    PokemonGen4.PICHU,
    PokemonGen4.ROSELIA,
    PokemonGen4.STARAVIA,
    PokemonGen4.KRICKETUNE,
    PokemonGen4.PIKACHU,
    PokemonGen4.CLEFAIRY,
    PokemonGen4.JIGGLYPUFF,
    PokemonGen4.MEOWTH,
    PokemonGen4.CHANSEY,
    PokemonGen4.EEVEE,
    PokemonGen4.CLEFFA,
    PokemonGen4.IGGLYBUFF,
    PokemonGen4.MARILL,
    PokemonGen4.AZURILL,
    PokemonGen4.PLUSLE,
    PokemonGen4.MINUN,
    PokemonGen4.CASTFORM,
    PokemonGen4.BONSLY,
    PokemonGen4.MIME_JR,
    PokemonGen4.HAPPINY,
    PokemonGen4.DITTO,
},
"Celestic Town": {
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.GYARADOS,
    PokemonGen4.CORPHISH,
    PokemonGen4.CRAWDAUNT,
    PokemonGen4.MAGIKARP,
    PokemonGen4.SEAKING,
    PokemonGen4.GOLDEEN,
},
"Celestic Ruins": {},
"Canalave City": {
    PokemonGen4.TENTACOOL,
    PokemonGen4.TENTACRUEL,
    PokemonGen4.GYARADOS,
    PokemonGen4.LUMINEON,
    PokemonGen4.STARYU,
    PokemonGen4.MAGIKARP,
    PokemonGen4.FINNEON,
    PokemonGen4.SHELLOS,
    PokemonGen4.GASTRODON,
},
"Iron Island": {
    PokemonGen4.GEODUDE,
    PokemonGen4.GRAVELER,
    PokemonGen4.ZUBAT,
    PokemonGen4.GOLBAT,
    PokemonGen4.ONIX,
    PokemonGen4.MAWILE,
    PokemonGen4.SABLEYE,
    PokemonGen4.STEELIX,
    PokemonGen4.RIOLU,
    PokemonGen4.TENTACOOL,
    PokemonGen4.WINGULL,
    PokemonGen4.TENTACRUEL,
    PokemonGen4.PELIPPER,
    PokemonGen4.GYARADOS,
    PokemonGen4.LUMINEON,
    PokemonGen4.QWILFISH,
    PokemonGen4.MAGIKARP,
    PokemonGen4.FINNEON,
    PokemonGen4.REGISTEEL,
},
"Lake Valor": {
    PokemonGen4.BIBAREL,
    PokemonGen4.STARAVIA,
    PokemonGen4.PSYDUCK,
    PokemonGen4.SOLROCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.LUNATONE,
    PokemonGen4.SEAKING,
    PokemonGen4.GYARADOS,
    PokemonGen4.GOLDEEN,
    PokemonGen4.MAGIKARP,
    PokemonGen4.WOBBUFFET,
    PokemonGen4.AZELF,
},
"Fuego Ironworks": {
    PokemonGen4.MAGNEMITE,
    PokemonGen4.MAGMAR,
    PokemonGen4.FLOATZEL,
    PokemonGen4.GASTRODON,
    PokemonGen4.TENTACOOL,
    PokemonGen4.SHELLOS,
    PokemonGen4.GYARADOS,
    PokemonGen4.LUMINEON,
    PokemonGen4.SHELLDER,
    PokemonGen4.MAGIKARP,
    PokemonGen4.FINNEON,
    PokemonGen4.ARON,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
},
"Valor Cavern": {},
"Acuity Lakefront": {
    PokemonGen4.SNEASEL,
    PokemonGen4.SNOVER,
    PokemonGen4.SNORUNT,
    PokemonGen4.SWINUB,
    PokemonGen4.URSARING,
},
"Snowpoint City": {
    PokemonGen4.HAUNTER,
},
"Lake Acuity": {
    PokemonGen4.PSYDUCK,
    PokemonGen4.SNEASEL,
    PokemonGen4.BIBAREL,
    PokemonGen4.SOLROCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.LUNATONE,
    PokemonGen4.SEAKING,
    PokemonGen4.GYARADOS,
    PokemonGen4.GOLDEEN,
    PokemonGen4.MAGIKARP,
    PokemonGen4.UXIE,
    PokemonGen4.SNOVER,
    PokemonGen4.SNORUNT,
    PokemonGen4.TEDDIURSA,
},
"Team Galactic HQ": {},
"Sunyshore City": {
    PokemonGen4.TENTACRUEL,
    PokemonGen4.PELIPPER,
    PokemonGen4.GYARADOS,
    PokemonGen4.OCTILLERY,
    PokemonGen4.MAGIKARP,
    PokemonGen4.REMORAID,
    PokemonGen4.TENTACOOL,
    PokemonGen4.WINGULL,
},
"Pokémon League": {
    PokemonGen4.TENTACRUEL,
    PokemonGen4.PELIPPER,
    PokemonGen4.GYARADOS,
    PokemonGen4.OCTILLERY,
    PokemonGen4.LUVDISC,
    PokemonGen4.MAGIKARP,
    PokemonGen4.REMORAID,
    PokemonGen4.WINGULL,
},
"Victory Road": {
    PokemonGen4.GRAVELER,
    PokemonGen4.GOLBAT,
    PokemonGen4.STEELIX,
    PokemonGen4.ONIX,
    PokemonGen4.FLOATZEL,
    PokemonGen4.GYARADOS,
    PokemonGen4.MAGIKARP,
    PokemonGen4.LAPRAS,
    PokemonGen4.GABITE,
    PokemonGen4.RHYHORN,
    PokemonGen4.RHYDON,
    PokemonGen4.MAGNETON,
    PokemonGen4.AZUMARILL,
    PokemonGen4.DEWGONG,
},
"Route 201",: {
    PokemonGen4.STARLY,
    PokemonGen4.BIDOOF,
    PokemonGen4.GROWLITHE,
    PokemonGen4.DODUO,
    PokemonGen4.KRICKETOT,
    PokemonGen4.NIDORAN_M,
    PokemonGen4.NIDORAN_F,
},
"Route 202": {
    PokemonGen4.STARLY,
    PokemonGen4.BIDOOF,
    PokemonGen4.SHINX,
    PokemonGen4.KRICKETOT,
    PokemonGen4.GROWLITHE,
    PokemonGen4.ZIGZAGOON,
    PokemonGen4.SENTRET,
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.SEAKING,
    PokemonGen4.GYARADOS,
    PokemonGen4.GOLDEEN,
    PokemonGen4.MAGIKARP,
},
"Route 203": {
    PokemonGen4.STARLY,
    PokemonGen4.BIDOOF,
    PokemonGen4.SHINX,
    PokemonGen4.ZUBAT,
    PokemonGen4.ABRA,
    PokemonGen4.KRICKETOT,
    PokemonGen4.PINECO,
    PokemonGen4.SEEDOT,
    PokemonGen4.LOTAD,
    PokemonGen4.CUBONE,
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.SEAKING,
    PokemonGen4.GYARADOS,
    PokemonGen4.GOLDEEN,
    PokemonGen4.MAGIKARP,
},
"Route 204": {
    PokemonGen4.STARLY,
    PokemonGen4.BIDOOF,
    PokemonGen4.BUDEW,
    PokemonGen4.ZUBAT,
    PokemonGen4.KRICKETOT,
    PokemonGen4.SHINX,
    PokemonGen4.PINECO,
    PokemonGen4.SEEDOT,
    PokemonGen4.LOTAD,
    PokemonGen4.SUNKERN,
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.SEAKING,
    PokemonGen4.GYARADOS,
    PokemonGen4.GOLDEEN,
    PokemonGen4.MAGIKARP,
    PokemonGen4.WURMPLE,
    PokemonGen4.CATERPIE,
    PokemonGen4.WEEDLE,
},
"Route 205": {
    PokemonGen4.BIDOOF,
    PokemonGen4.LOTAD,
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.GYARADOS,
    PokemonGen4.WHISCASH,
    PokemonGen4.MAGIKARP,
    PokemonGen4.BARBOACH,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.SHELLOS,
    PokemonGen4.PACHIRISU,
    PokemonGen4.BUIZEL,
    PokemonGen4.TENTACOOL,
    PokemonGen4.TENTACRUEL,
    PokemonGen4.LUMINEON,
    PokemonGen4.SHELLDER,
    PokemonGen4.FINNEON,
    PokemonGen4.LUMINEON,
    PokemonGen4.HOPPIP,
    PokemonGen4.BUDEW,
    PokemonGen4.BEAUTIFLY,
    PokemonGen4.DUSTOX,
    PokemonGen4.HOOTHOOT,
    PokemonGen4.SILCOON,
    PokemonGen4.CASCOON,
    PokemonGen4.KRICKETOT,
    PokemonGen4.SLOWPOKE,
    PokemonGen4.GASTRODON,
},
"Route 206": {
    PokemonGen4.GEODUDE,
    PokemonGen4.PONYTA,
    PokemonGen4.ZUBAT,
    PokemonGen4.KRICKETUNE,
    PokemonGen4.GLIGAR,
    PokemonGen4.BALTOY,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.MACHOP,
    PokemonGen4.LARVITAR,
},
"Route 207": {
    PokemonGen4.MACHOP,
    PokemonGen4.GEODUDE,
    PokemonGen4.ZUBAT,
    PokemonGen4.KRICKETOT,
    PokemonGen4.PHANPY,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.PONYTA,
    PokemonGen4.STANTLER,
},
"Route 208": {
    PokemonGen4.PSYDUCK,
    PokemonGen4.ZUBAT,
    PokemonGen4.BIDOOF,
    PokemonGen4.BIBAREL,
    PokemonGen4.ZANGOOSE,
    PokemonGen4.SEVIPER,
    PokemonGen4.DUNSPARCE,
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.GYARADOS,
    PokemonGen4.MAGIKARP,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.BUDEW,
    PokemonGen4.RALTS,
    PokemonGen4.ROSELIA,
    PokemonGen4.SEAKING,
    PokemonGen4.GOLDEEN,
    PokemonGen4.SMEARGLE,
},
"Route 209": {
    PokemonGen4.STARAVIA,
    PokemonGen4.BIBAREL,
    PokemonGen4.CHANSEY,
    PokemonGen4.ZUBAT,
    PokemonGen4.VULPIX,
    PokemonGen4.SNUBBULL,
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.SEAKING,
    PokemonGen4.GYARADOS,
    PokemonGen4.GOLDEEN,
    PokemonGen4.MAGIKARP,
    PokemonGen4.SPIRITOMB,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.ROSELIA,
    PokemonGen4.RALTS,
    PokemonGen4.DUSKULL,
    PokemonGen4.KIRLIA,
},
"Route 210": {
    PokemonGen4.MEDITITE,
    PokemonGen4.PSYDUCK,
    PokemonGen4.MACHOP,
    PokemonGen4.MACHOKE,
    PokemonGen4.HOOTHOOT,
    PokemonGen4.NOCTOWL,
    PokemonGen4.BIBAREL,
    PokemonGen4.ZANGOOSE,
    PokemonGen4.SEVIPER,
    PokemonGen4.GOLDUCK,
    PokemonGen4.GYARADOS,
    PokemonGen4.WHISCASH,
    PokemonGen4.MAGIKARP,
    PokemonGen4.BARBOACH,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.SWABLU,
    PokemonGen4.SCYTHER,
    PokemonGen4.BAGON,
},
"Route 211": {
    PokemonGen4.MEDITITE,
    PokemonGen4.ZUBAT,
    PokemonGen4.MACHOKE,
    PokemonGen4.GRAVELER,
    PokemonGen4.NOCTOWL,
    PokemonGen4.CHINGLING,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.BIDOOF,
    PokemonGen4.TYROGUE,
    PokemonGen4.BRONZOR,
},
"Route 212": {
    PokemonGen4.STARAVIA,
    PokemonGen4.ROSELIA,
    PokemonGen4.GOLDUCK,
    PokemonGen4.SEAKING,
    PokemonGen4.GYARADOS,
    PokemonGen4.GOLDEEN,
    PokemonGen4.MAGIKARP,
    PokemonGen4.SMEARGLE,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.EKANS,
    PokemonGen4.LOTAD,
    PokemonGen4.LOMBRE,
    PokemonGen4.WOOPER,
    PokemonGen4.QUAGSIRE,
    PokemonGen4.GYARADOS,
    PokemonGen4.WHISCASH,
    PokemonGen4.MAGIKARP,
    PokemonGen4.GRIMER,
    PokemonGen4.MARILL,
    PokemonGen4.KIRLIA,
    PokemonGen4.PSYDUCK,
    PokemonGen4.SHELLOS,
    PokemonGen4.BUIZEL,
    PokemonGen4.CROAGUNK,
    PokemonGen4.TENTACOOL,
    PokemonGen4.TENTACRUEL,
    PokemonGen4.GASTRODON,
    PokemonGen4.OCTILLERY,
    PokemonGen4.REMORAID,
},
"Route 213": {
    PokemonGen4.BUIZEL,
    PokemonGen4.SHELLOS,
    PokemonGen4.WINGULL,
    PokemonGen4.TENTACOOL,
    PokemonGen4.WINGULL,
    PokemonGen4.TENTACRUEL,
    PokemonGen4.GYARADOS,
    PokemonGen4.OCTILLERY,
    PokemonGen4.MAGIKARP,
    PokemonGen4.REMORAID,
    PokemonGen4.SWELLOW,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.CHATOT,
    PokemonGen4.GASTRODON,
},
"Route 214": {
    PokemonGen4.GRAVELER,
    PokemonGen4.GEODUDE,
    PokemonGen4.VULPIX,
    PokemonGen4.SPOINK,
    PokemonGen4.PSYDUCK,
    PokemonGen4.GOLDUCK,
    PokemonGen4.SEAKING,
    PokemonGen4.GYARADOS,
    PokemonGen4.GOLDEEN,
    PokemonGen4.MAGIKARP,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.RHYHORN,
    PokemonGen4.HOUNDOUR,
    PokemonGen4.POOCHYENA,
},
"Route 215": {
    PokemonGen4.ABRA,
    PokemonGen4.KADABRA,
    PokemonGen4.DROWZEE,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.MARILL,
    PokemonGen4.STARAVIA,
    PokemonGen4.SCYTHER,
    PokemonGen4.LICKITUNG,
},
"Route 216": {
    PokemonGen4.SNEASEL,
    PokemonGen4.SNOVER,
    PokemonGen4.GRAVELER,
    PokemonGen4.ZUBAT,
    PokemonGen4.MEDITITE,
    PokemonGen4.URSARING,
    PokemonGen4.SNORUNT,
},
"Route 217": {
    PokemonGen4.SNEASEL,
    PokemonGen4.SNOVER,
    PokemonGen4.SWINUB,
    PokemonGen4.SNORUNT,
    PokemonGen4.URSARING,
    PokemonGen4.PILOSWINE,
    PokemonGen4.DELIBIRD,
},
"Route 218": {
    PokemonGen4.FLOATZEL,
    PokemonGen4.GASTRODON,
    PokemonGen4.VOLTORB,
    PokemonGen4.TENTACOOL,
    PokemonGen4.SHELLOS,
    PokemonGen4.TENTACRUEL,
    PokemonGen4.GYARADOS,
    PokemonGen4.LUMINEON,
    PokemonGen4.MAGIKARP,
    PokemonGen4.FINNEON,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.MR_MIME,
    PokemonGen4.CHATOT,
},
"Route 222": {
    PokemonGen4.FLOATZEL,
    PokemonGen4.PELIPPER,
    PokemonGen4.WINGULL,
    PokemonGen4.CHATOT,
    PokemonGen4.SKITTY,
    PokemonGen4.TENTACOOL,
    PokemonGen4.TENTACRUEL,
    PokemonGen4.GYARADOS,
    PokemonGen4.OCTILLERY,
    PokemonGen4.MAGIKARP,
    PokemonGen4.REMORAID,
    PokemonGen4.FLAAFFY,
    PokemonGen4.WURMPLE,
    PokemonGen4.MUNCHLAX,
    PokemonGen4.HERACROSS,
    PokemonGen4.AIPOM,
    PokemonGen4.BURMY,
    PokemonGen4.COMBEE,
    PokemonGen4.CHERUBI,
    PokemonGen4.ELECTABUZZ,
    PokemonGen4.MAGNETON,
    PokemonGen4.MAGNEMITE,
    PokemonGen4.LUXIO,
},
"Route 223": {
    PokemonGen4.TENTACRUEL,
    PokemonGen4.PELIPPER,
    PokemonGen4.MANTYKE,
    PokemonGen4.GYARADOS,
    PokemonGen4.OCTILLERY,
    PokemonGen4.MAGIKARP,
    PokemonGen4.REMORAID,
},
    },
    important_battles=[
        "Route 203 - Rival (9)",
        "Oreburgh City - GymTrainer (14)",
        "Jubilife City - Rival (13)",
        "Valley Windworks - Boss (17)",
        "Eterna City - GymTrainer (22)",
        "Eterna City - Boss (23)",
        "Hearthome City - GymTrainer (26)",
        "Route 209 - Rival (29)",
        "Veilstone City - GymTrainer (32)",
        "Veilstone City - Rival (27)",
        "Pastoria City - Rival (36)",
        "Pastoria City - GymTrainer (37)",
        "Celestic Town - Boss (36)",
        "Canalave City - Rival (38)",
        "Canalave City - GymTrainer (41)",
        "Lake Valor - Boss (40)",
        "Lake Verity - Boss (40)",
        "Snowpoint City - GymTrainer (44)",
        "Veilstone City - Boss (44)",
        "Spear Pillar - Boss (46)",
        "Distortion World - Boss (48)",
        "Sunnyshore City - Boss (50)",
        "Pokémon League - Rival (51)",
    ]
)


HEART_GOLD = None


SOUL_SILVER = None
